slatedb/slatedb

README.md
src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_executor.rs
src/compactor_state.rs
src/config.rs
src/db.rs
src/lib.rs

- Move all WriterConfig, ReaderConfig, and CompactorConfig to `config.rs`.
- Add a smidge of documentation to `flush_ms`.
- Replace the compactor poll interval constant with a default constant to make
it look like the other defaults. This required a `.clone()` in the bench test
because the Tokio executor clones itself (and takes ownership of the options
lifetime).
- Update `compactor_execute_bench.rs` to use `DEFAULT_COMPACTOR_OPTIONS`.

Centralize config in `config.rs`

---

README.md
src/lib.rs

- Make the config mod public.
- Add `async` to `main`  in example code.

Minor fixes to enable crates.io

---

README.md
src/compactor.rs
src/compactor_state.rs
src/config.rs
src/db.rs

- Addresses #113 
- Created new method `Db::open_with_opts` to simplify `Db::open`. 
Chosen default 
```rust
{
flush_ms: 100,
manifest_poll_interval: Duration::from_secs(1),
min_filter_keys: 1000,
l0_sst_size_bytes: 128,
compactor_options: Some(CompactorOptions::default()),
}
```

Create `DbOptions::default()` and `Db::open_with_opts`

---

README.md
src/lib.rs

This embeds the readme in the module docstring, so that it appears on docs.rs. Here's what it looks like:
It also adds a badge to the readme linking to the docs.

Link to docs.rs and embed readme in it

---

src/compactor.rs
src/compactor_executor.rs
src/db.rs
src/mem_table_flush.rs

The compactor orchestrator was not shutting down the compactor executor when it
received a shutdown message. Instead, it was immediately returning. This
results in spurious error messages when the compactor executor continues trying
to complete compaction jobs after the channel is closed.
I've added code to shutdown the executor and drain the remaining compaction
messages before halting the orchestrator.

Close compactor executor on shutdown

---

src/compactor.rs
src/mem_table_flush.rs

Per #133 discussion, I'm adding closing logic for `load_manifest` calls in the memtable and compactor loops. Previously, ticks that occur in these loops after stopping were still run. Now, the ticks are ignored. There wasn't anything terrible about that, but it could trigger commpactions or flushes after shutdown, which isn't ideal.

Skip manifest reload when compactor and memtable flusher are closed

---

src/tablestore.rs

Use transactional object store for writing wal ssts. 
This is towards completing *Write fence writes to wal to lock older writers* in #53 .

Use transactional object store for wal writes

---

schemas/sst.fbs
src/compactor.rs
src/compactor_executor.rs
src/db.rs
src/db_state.rs
src/flatbuffer_types.rs
src/generated/manifest_generated.rs
src/sorted_run_iterator.rs
src/sst.rs
src/sst_iter.rs
src/tablestore.rs

This patch moves the sst index out of the sst info footer and into its own data block that sits just before the footer. The index can grow quite large, and therefore we don't want to require that it be stored in memory, or put it in the manifest. Instead, this patch changes the read path to load the index by reading it from the sst when its needed.

move sst index into its own data block

---

README.md
docs/0001-manifest.md
src/compactor.rs
src/config.rs
src/db.rs
src/flush.rs

Given we already use `Duration` for other interval fields, this one looked out of place. 
Change `flush_ms` to `flush_interval` to make it uniform.

Change flush_ms to flush_interval

---

Cargo.toml
README.md
src/compactor.rs
src/config.rs
src/db.rs

This patch adds the ability to disable the WAL. Some use cases may not require SlateDB to maintain its own WAL and prefer not to take on the cost of maintianing the WAL and restoring it. This patch allows clients of the DB to disable the WAL using a db option. Because this option is a bit risky - we wouldn't want it to be set to false by mistake - it's only enabled when a rust feature called wal_disable is enabled.

support disabling the WAL

---

schemas/sst.fbs
src/db_state.rs
src/flatbuffer_types.rs
src/generated/manifest_generated.rs
src/sst.rs

Based on ##141
Storing the Compression Codec in sst-info file for every SST created in db. Using sst-info to decompress the SST block.

Support changing the compression codec on an initialized db

---

src/db.rs
src/db_state.rs
src/mem_table_flush.rs

- Set the wal id associated with a memtable to the last wal id rather than the last compacted wal id. This ensures we avoid replaying wal entries on a restart.
- Notify waiters after flushing an imm memtable

fix a couple bugs in the wal_disable feature

---

Cargo.lock
Cargo.toml
src/compaction_execute_bench/compaction_execute_bench.rs
src/config.rs
src/db_bench/args.rs
src/db_bench/db_bench.rs
src/db_bench/main.rs
src/db_bench/s3.rs

This patch adds a tool for load testing SlateDB. The tool is configured using command-line args. Currently, it only supports write-only workloads over a random keyspace.
The general syntax for the command line looks like: `db_bench <db opts> COMMAND <command opts>`
`<db opts>` let you configure database options.
`<command opts>` let you configure the bench command
Currently the only command that is supported is write, which generates a pure write workload.
for example:
```bash
$ db-bench -c aws -r us-west-2 -b rohan-test-slatedb -p test-2 --disable-wal true \
--flush-ms 100 --l0-sst-size-bytes 67108864 \
write \
--key-distribution Random --key-len 32 --val-len 256
```

add db bench tool

---

README.md
src/compactor.rs
src/compactor_executor.rs
src/compactor_state.rs
src/config.rs
src/db.rs
src/db_bench/args.rs
src/db_common.rs
src/db_state.rs
src/flush.rs
src/lib.rs
src/mem_table.rs
src/mem_table_flush.rs
src/size_tiered_compaction.rs

this patch fills in the size-tiered compaction policy and adds a crude backpressure mechanism to throttle writes if they are arriving faster than the db can compact:
Updates SizeTieredCompactionPolicy so that it compacts sorted runs under compacted. The policy works by looking for sequences of runs that are all similarly sized. Similarly sized is determined by an option to the policy called include_size_threshold. A SR is included in a given sequence if it's size is less than include_size_threshold multiplied by the size of the smallest run that is already in the sequence.
The policy eliminates sequences that violate the following constraints:
- conflicts: A compaction is eliminated if it includes a source for which there is already a compaction running.
- backpressure: A compaction is …

implement compaction policy with backpressure

---

src/filter.rs

It looks like the only call-site only provides values from `self` that the function `filter_size_bytes` itself has access to.

Simplify BloomFilterBuilder.filter_bytes

---

src/compactor.rs
src/config.rs
src/db.rs

This patch makes the tokio handle for the compactor configurable. This way the client can isolate the compactor to its own worker pool so that it doesn't compete for access to the thread pool used by the main runtime which serves reads/writes.

make compactor tokio handle configurable

---

rustfmt.toml

sadly it turns out `group_imports = StdExternalCrate` is still in nightly, we can not use the merge import format rule with stable rust.
```
Warning: can't set `normalize_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = StdExternalCrate`, unstable features are only available in nightly channel.
Warning: can't set `normalize_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = StdExternalCrate`, unstable features are only available in nightly channel.
Warning: can't set `normalize_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `group_imports = StdExternalCrate`, unstable features are only available in nightly channel.
```
we …

fix: use stable in rustfmt.toml 

---

schemas/sst.fbs
src/flatbuffer_types.rs
src/generated/manifest_generated.rs

Fixes: #97
This PR makes the following two fields `CompactedSstId` and `SsTableInfo` required.
Rest of the fields can't be changed to required as they are scalars
The following fields have been left as optional in line with this comment  https://github.com/slatedb/slatedb/issues/97#issuecomment-2308542303
- `ManifestV1.snapshots`
- `ManifestV1.l0_last_compacted`
- `SsTableInfo.first_key`

manifest: make fields required

---

src/db_bench/main.rs

Fixes #192
We were seeing `JoinError::Cancelled` errors when running `db-bench`. Oddly, it was only with the release binary. I eventually realized it's becasue we're just breaking the main loop in `db_bench.rs`'s `run()` method. When the loop breaks, the process returns almost immediately. The code never shuts down the `db` object. If the compactor executor is running, it'll throw these cancellation messages.

Close `db` in `db-bench` tool to prevent `JoinError::Cancelled` messages

---

CONTRIBUTING.md

i saw a bunch of new PRs with red CI so I thought we should explicitly mention all these steps for new contributors and rustaceans to make their first PR experience smoother.
I also think we should move the schema generation instructions out of the generated folder into the Contributing.md so that all the development steps are available in one document and not scattered. Let me know if you would like me to make that change in this PR too.

Add some steps to CONTRIBUTING.md

---

src/cached_object_store.rs

after this PR was applied, the script (https://gist.github.com/flaneur2020/bd03c6d9032828c379a86c7ddeb8db32) successfully finished after approximately 15 minutes with a peak RES of about 500+ MB.
~it appears that this memory usage is not actually a leak, but rather a reserved memory buffer from the memory allocator. this buffer tends to grow and is not released to the OS immediately. the earlier code allocated the buffer in part_size, which might not have been very friendly to the allocator's buffer management.~
from @rodesai :
> I don't think it's a problem with the allocator's buffer management per se. I think that's happening is that we were returning the Bytes returned from slice here, which doesn't allocate a new buffer, but instead just adds a reference to the underlying buffer that …

fix(cache): oom when enabled object store cache

---

.gitignore
Cargo.lock
Cargo.toml
src/admin.rs
src/cli/args.rs
src/cli/main.rs
src/db_state.rs
src/flatbuffer_types.rs
src/lib.rs
src/manifest.rs
src/manifest_store.rs

This is the first step to implementing and Admin CLI, as the result of the discussion on #151 and the discord channel. Note that this specific PR does not spin up an entire embedded SlateDB instance and instead just directly leverages the ability to read the manifest, this makes it really fast!
```
$ target/release/slatedb --path store2375 read-manifest | jq .
[
36,
{
"core": {
"l0_last_compacted": "01J7M9NRAGXPV967CK920R7EFT",
"l0": [
{
"id": {
"Compacted": "01J7MDQE553EWN2MV7JM2JJ13Z"
},
"info": {
"data_length": 72
}
},
{
"id": {
"Compacted": "01J7MDP1AFRMF7KGK9H3D64K1Q"
},
"info": {
"data_length": 72
}
}
],
"compacted": [
{
"id": 0,
"ssts": [
{
"id": {
"Compacted": "01J7M9NWFP9BMW733J4BH5VRV4"
},
"info": {
"data_length": 72
}
}
]
}
],
"next_wal_sst_id": 1,
"last_compacted_wal_sst_id": …
```

first pass at slatedb read-manifest CLI

---

Cargo.toml

The `admin.rs` file is using `dotenvy` for `load_object_store_from_env`. Since the admin package is meant to be used outside of the `cli` feature, I opted to include `dotenvy` as a dependency in all binaries rather than introduce another `admin` feature or wrap the `dotenvy` usage in the `cli` feature..

Use `dotenvy` crate for all binaries

---

src/admin.rs
src/cli/args.rs
src/cli/main.rs
src/manifest_store.rs

This adds more of the functionality requested in #151. See below for behavior:
```
$ target/release/slatedb --path store2375 read-manifest -i 32 | jq .
[
32,
{
"core": {
"l0_last_compacted": "01J7M9NRAGXPV967CK920R7EFT",
"l0": [
{...
}
]
```
```
$ target/release/slatedb --path store2375 read-manifest -i 37
No manifest file found.
```
```
$ target/release/slatedb --path store2375 list-manifests | jq .
[
{
"id": 1,
"location": "00000000000000000001.manifest",
"last_modified": "2024-09-12T23:38:34Z",
"size": 44
},
{
"id": 2,
"location": "00000000000000000002.manifest",
"last_modified": "2024-09-12T23:38:35Z",
"size": 56
},
{
"id": 3,
"location": "00000000000000000003.manifest",
"last_modified": "2024-09-12T23:38:35Z",
"size": 64
},
```
```
$ target/release/slatedb --path store2375 …
```

support list-manifests and read specific manifest for slatedb CLI

---

Cargo.lock
Cargo.toml
src/config.rs
src/db_state.rs
src/flatbuffer_types.rs
src/size_tiered_compaction.rs
src/sst.rs

We've been passing FlatBuffer objects around for SST info data. We've been wrapping these objects in `SsTableInfoOwned` because FlatBuffer's code generated structs don't allow borrwing easily. This leads to some annoying side effects:
- We're using FlatBuffer APIs all over the place
- We're using `.borrow()` everywhere
The Manifest doesn't work this way. Instead, we have a normal Rust struct for Manifest and we have a codec to convert back and forth between the FlatBuffer Manifest and our own. This PR makes SsTableInfo behave like Manifest.
The drawback to our new approach is that we don't lazy decode the FlatBuffer like we used to. This could impact performance in some cases. In practice, I suspect it'll be negligible. Still, we should run some tests to verify.
Fixes #213

Remove `SsTableInfoOwned` and add `SsTableInfo`

---

src/compaction_execute_bench.rs
src/compactor.rs
src/config.rs
src/db.rs
src/garbage_collector.rs
src/sorted_run_iterator.rs
src/sst.rs
src/sst_iter.rs
src/tablestore.rs

adds a new db opt named filter_bits_per_key which lets the user specify the number of filter bits to use per key for each bloom filter.
also changes the way that SsTableFormat is built to use a builder rather than a new() method with a bunch of parameters. This will let us add new format parameters without having to change all the places where we create a format

support configuring the filter bits per key

---

src/db.rs
src/filter.rs
src/sst.rs

Implement _hash sharing_ in [Reducing Bloom Filter CPU Overhead in LSM-Trees on Modern Storage Devices](https://dl.acm.org/doi/10.1145/3465998.3466002)
The idea is very simple and intuitive. In the point query of LSM, we need to probe the filter. Since the key remains unchanged, we only need to calculate the hash value once and pass the hash value to filter. So we can reduce the hash overhead of the filter during each point query.
In addition, we may be able to implement hash sharing during the construction process of SSTable. For example, in levels below L0, the same key may be arranged together with different values. In SSTable Builder we can use a field named `last_key_hash`, and every time a new key is added, we compare it with `last_key`. If it is the same, we can avoid the hash cost …

feat(filter): implement hash sharing to reduce filter cost

---

rustfmt.toml
src/inmemory_cache.rs
src/sst_iter.rs
src/tablestore.rs

This PR introduces in-memory cache for Bloom filters and Sst Indexes and removes the filter map in TableStore

cache indexes and bloom filters in memory

---

specs/kvstore/KeyValueStore.fizz

Making some changes to actually reflect the design.
1.  Use chronologically sortable id for L0 names (to model ULID)
2.  Does not handle flush thread crashes (`crash_on_yield: false`)
3.  Support only a single flush thread (`max_concurrent_actions: 1`)
4.  Add assertion that uncommitted read always returns last put value
5.  Add assertion that committed read eventually returns the last put value
6.  Add an assertion MaxObjects as safety check. 
-  The MaxObjects in the ObjectStore should be at most 2*number of Puts.
-  Violating 2 and 3 above will fail MaxObjects check
There is a small bit that deviates from the actual design. The FlushWal and FlushMemtable are modeled as separate actions, instead of FlushWal triggering FlushMemtable as an option. One implication is there could be two …

Use ulid, no crash protection, single flush thread

---

src/s3_bench/main.rs

[#234](https://github.com/slatedb/slatedb/pull/234) forgot to modify `s3_bench.rs`. Therefore `s3_bench.rs` cannot find the relevant modules.

fix(bench): fix s3_bench can't find cache module

---

README.md

Without those, I'd get build errors due to the unresolveable imports in the hello world example:
```
error[E0432]: unresolved import `bytes`
--> src/main.rs:1:5
|
1 | use bytes::Bytes;
|     ^^^^^ use of undeclared crate or module `bytes`
error[E0433]: failed to resolve: use of undeclared crate or module `object_store`
--> src/main.rs:2:5
|
2 | use object_store::{ObjectStore, memory::InMemory, path::Path};
|     ^^^^^^^^^^^^ use of undeclared crate or module `object_store`
error[E0432]: unresolved import `object_store`
--> src/main.rs:2:5
|
2 | use object_store::{ObjectStore, memory::InMemory, path::Path};
|     ^^^^^^^^^^^^ use of undeclared crate or module `object_store`
error[E0433]: failed to resolve: use of undeclared crate or module `tokio`
--> src/main.rs:7:3
|
7 | #[tokio::main]
| …
```

Adding missing dependencies to README

---

src/block.rs
src/db_cache.rs
src/db_cache/foyer.rs
src/db_cache/moka.rs
src/filter.rs
src/flatbuffer_types.rs
src/s3_bench/main.rs
src/sst.rs

Calculate the size of each cached item based on their content. Since other cache implementations might use similar weights mechanisms, the CachedEntry::size method is declared public.
Fixes #241

fix(cache): Use the cached entries size as weights to calculate the size of the cache

---

src/block.rs
src/block_iterator.rs
src/sst_iter.rs

Solve #237.
Adding prefix key encoding for slateDB.

feat(block): support prefix key encoding

---

src/config.rs

I noticed that we fail with a compiler error if we build without the foyer feature. It looks like the if statements in our block cache config are still compiled even if the feature is not enabled. I switched to use a macro instead to prevent compiling foyer code when the foyer feature is not enabled.

Use macros instead of if's for block cache config

---

src/db.rs
src/db_state.rs
src/sst_iter.rs

Fixes: #185
I come from a Go background haven't written much async Rust so please let me know if anything is non-idiomatic.
I only tried to parallelize the part which reads and buffers the wal items, left the memtable building part out of the tokio task as that was acquiring a lock and I thought it might get complicated and lead to deadlocks, etc. I am also assuming that the intent of the issue was also to simply parallelize the wal fetch part excluding memtable building. Let me know if I got that wrong.
In a nutshell does the following:
- ~Extracts the logic which opens SST and iterates over WAL entries to a seperate method `fetch_wall`~
- ~wraps the aforementioned method as a tokio task~
- ~Runs all the tasks in parallel using `join_all`~
- ~Iterates over the results of all the tasks …

Fetch WALs in parallel on recovery

---

src/admin.rs
src/bencher/README.md

It is useful for running admin commands or for testing to support the AWS session token

Allow AWS session token for admin/testing

---

src/db.rs
src/flush.rs
src/mem_table_flush.rs

Fixes https://github.com/slatedb/slatedb/issues/235. Currently `Db.flush` executes the flush from the calling thread. It should instead send a message to the flush thread to do the work and wait for a response (the same as how memtables are flushed).

Db.flush should await flush from background thread

---

schemas/sst.fbs
src/block_iterator.rs
src/flatbuffer_types.rs
src/generated/manifest_generated.rs
src/row_codec.rs

This patch is the second in the series to implement #218 (RFC-3), and persists the row attributes into the SST files themselves. The only row attribute is currently just `RowFlags` which was introduced in #251.
This PR also addresses the comments from @rodesai on the previous PR post-merge.

[2/N] RFC-3: persist row attributes in the SST

---

Cargo.lock
Cargo.toml
src/bencher/README.md
src/bencher/SlateDb.toml
src/bencher/args.rs
src/bencher/benchmark-db.sh
src/bencher/main.rs
src/config.rs
src/error.rs
src/size_tiered_compaction.rs

This change adds these functions to allow loading DbOptions from configuration files or environment variables:
`from_file`: loads the options from a specific file.
`from_env`: loads the options from environment variables with a specific prefix.
`load`: loads the options with some default file locations and `SLATEDB_` as a default prefix. This option is accumulative. If a config file exists, and environment variables also exist, both are combined. Environment variables override settings in the configuration file.
I was going to document all this and provide additional configuration examples, but I could not find a good place to do it. Let me know where I should add that @criccomini. If this repo doesn't include the documentation, I'll be happy to open a new PR in a different repository for …

feat(db): Allow loading DbOptions from a configuration file or environment variables

---

rfcs/0003-timestamps-and-ttl.md
schemas/sst.fbs
src/batch_write.rs
src/block.rs
src/block_iterator.rs
src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_executor.rs
src/config.rs
src/db.rs
src/db_state.rs
src/flatbuffer_types.rs
src/flush.rs
src/garbage_collector.rs
src/generated/manifest_generated.rs
src/mem_table.rs
src/merge_iterator.rs
src/row_codec.rs
src/size_tiered_compaction.rs
src/sorted_run_iterator.rs
src/sst.rs
src/sst_iter.rs
src/tablestore.rs
src/test_utils.rs
src/types.rs

This is the third PR in the sequence to implement #228. It adds timestamps into the row format and encodes them into the SSTs using a custom-defined clock.
1. check `config.rs` for the `Clock` trait definition and default implementations
2. look at `db.rs` which uses the clock to seed the timestamp
3. follow the plumbing all the way through to `row_codec.rs`, where the values are encoded/decoded
4. confirm size computations in `mem_table.rs` are valid
5. look at test changes, starting with `test_utils.rs` which defines a test clock and confirms timestamps during iteration

[3/N] RFC-3: add timestamps

---

src/db.rs
src/tablestore.rs

Addresses the bug reported by [Writer Fencing Fizzbee spec](https://github.com/slatedb/slatedb/pull/266)
* Read the latest manifest and next WAL ID before writing the updated writer manifest and fencing WAL.

Fix race condition in writer fencing  that could result in two writers being open at the same time.

---

src/compaction_execute_bench.rs
src/config.rs

Currently run the `bencher compaction load` fails with the following error:
```
thread 'main' panicked at /Users/jason/Code/slatedb/src/compaction_execute_bench.rs:91:18:
join failed: JoinError::Panic(Id(14), "Timestamp RowAttribute was enabled for SST but attempted to insert a row with no timestamp.", ...)
```
This patch just uses current time to provide the missing timestamp. We could alternatively disable it in the row attributes or provide some other way to seed the values, but this seemed like the simplest thing for now.

Include timestamp when loading tables for compaction bench

---

src/error.rs

resolves #273 
is displaying the whole message too verbose or using the `.description()` output of `object_store::Error` is enough? ( ie `Object store error: Error :: InvalidPath` )

Display more verbose object store error message

---

schemas/sst.fbs
src/batch.rs
src/batch_write.rs
src/bencher/db.rs
src/block.rs
src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_executor.rs
src/config.rs
src/db.rs
src/db_state.rs
src/flatbuffer_types.rs
src/generated/manifest_generated.rs
src/mem_table.rs
src/merge_iterator.rs
src/row_codec.rs
src/sst.rs
src/sst_iter.rs
src/test_utils.rs
src/types.rs

This PR adds the physical component of TTL in accordance to RFC-3 (#228). It functions by encoding an `expire_ts` in the row as its written to the SST and then filters out rows during compaction that have already expired. Some intricacies:
- added `PutOption` to the public API to have something that is applied per-row (compared to `WriteOption` that is only applied per-write, which may contain multiple rows)
- added a clock to the `CompactorOptions` so that the timestamp of compaction can be set (this determines the "now" timestamp for expiration)
See the PR sequence for more background:
- #251 
- #258 
- #265 
Follow-Ups:

[4/N] RFC-3: add support for ttl expiry during compaction

---

src/bencher/args.rs
src/bencher/benchmark-db.sh
src/bencher/main.rs

The bencher was sometimes failing with an object store error. It turns out, we weren't closing the DB after running bencher. This could sometimes cause threads to try and flush after the runtime was shutdown but before the process was halted.
The PR also adds a run_bench method so we can include put/concurrency args into the object store paths. Previously, all benchmarks were writing into the same directory.
Fixes #291

Close DB in bencher

---

src/batch_write.rs
src/bencher/db.rs
src/compactor.rs
src/compactor_state.rs
src/db.rs

This PR migrates all put/delete calls to use write batches (and thus, the commit
pipeline). For single row operations, a batch with one row is created under the
hood. The PR also includes two other changes:
The `write_with_options` method returns a `Result<(), SlateDbError>`. Now that
we use this method for puts and deletes, they need to unwrap or forward the
results. I opted to forward them, as this lays the groundwork for #111. Note
that, though we now return a `Result`, it only returns `Ok` right now in the
commit pipeline. #111 must forward actual errors as they occur.
I noticed that I moved backpressure into the commit pipeline (batch write loop)
in a separate thread in #264. This works fine for tasks that have `WriteOptions`
where `await_durable` is true, but for `await_durable` set …

Unify write commit pipe

---

src/bencher/benchmark-db.sh

The bencher script isn't actually using `SlateDB.toml` because we require users to run the command from the project root. I've fixed this by passing the file location in directly as a `db-options-path` rather than letting Figment search for it.

Use SlateDB.toml in bencher

---

src/batch_write.rs
src/db.rs
src/db_common.rs
src/error.rs
src/flush.rs
src/mem_table_flush.rs

This change propagates write errors to the application using SlateDB.
I've removed the calls to `expect` that cause the process to panic on error, and wrapped a few missing errors into SlateDbError. I've also unified `MemtableFlushThreadMsg` and `WallFlushThreadMsg` into a single structure because the looked redundant.
@criccomini the only panic that I was not sure about is this code below introduced in https://github.com/slatedb/slatedb/pull/264/files#diff-51529babecd6e4018b78a49622df5b5d2c480476389ec07c0b4943d8bdbaa35eR71. To me, it looks like that code is never going to be reachable because the `if` clause always returns true if the feature flag `wal_disable` is not enabled. It makes me wonder if this feature flag is even useful for people. It doesn't look like it adds any additional …

chore(db): Propagate errors to the client.

---

README.md
src/config.rs
src/db.rs
src/db_cache/foyer.rs
src/db_cache/moka.rs
src/lib.rs
src/tablestore.rs

SlateDB uses a `Path` struct from `object_store`, this is not always evident when you start using the crate, and it can be confusing because `Path` is pretty well known from the standard library.
To make it easy to start with a new database, the `open` operations take now a generic that can be converted to a `object_store::path::Path`, which removes the direct dependency from the structure in the caller.
This change also re-exports `object_store` and `fail_parallel` so SlateDB provides all the main dependencies without having to fiddle with additional crates in the project directly.
Since the `db` module was not very well documented, and it's the core of the project, I decided to document all the public functions that users regularly interact with.
The main changes are in `src/db.rs` …

chore(db): Improve DB initialization and docs.

---

src/db.rs
src/db_common.rs
src/error.rs
src/flush.rs
src/mem_table_flush.rs

Use two different enums to represent flushing both structures since they can have different semantics.
/cc @rodesai

chore: Separate WAL and MemTable flushing mechanisms.

---

src/cached_object_store.rs
src/cached_object_store/fs_cache_storage.rs
src/db.rs

I was looking into #177 and I started to think that it might be better to split it into different PRs to avoid a massive change like I did with #231.
So this first change only moves things around to have a better structure to implement multiple storage backends for the object cache. The change should be backwards compatible since it doesn't really change any functionality.

refactor(cached_object_store): Move FsCacheStorage into a new module.

---

src/db.rs

Add docs warning that blocks are held in memory when get() returns

---

Cargo.lock
Cargo.toml
rfcs/0004-checkpoints.md
schemas/manifest.fbs
src/checkpoint.rs
src/config.rs
src/db_state.rs
src/flatbuffer_types.rs
src/generated/manifest_generated.rs
src/lib.rs
src/manifest.rs
src/manifest_store.rs
src/size_tiered_compaction.rs

This patch adds the manifest model for checkpoints
- Changes usage of the term "snapshot" to "checkpoint" in the manifest schema.
- adds the checkpoint_create_time_s, id, and metadata fields to checkpoint table
- adds the initialized field to the manifest (this is always set to true for now)
- plumbing for storing checkpoints in CoreDbState and encoding/decoding to/from the manifest bytes.
Also adds the initial API for creating checkpoints (from arbitrary clients and not the main db writer - this will be added in a later commit)
Review Guide:
- Review the changes to manifest.fbs
- Review the changes to `CoreDbState` that adds checkpoints and the plumbing to encode/decode these in the manifest
- Review the new API for checkpoint creation (the `create_checkpoint` API and the associated …

[1/N] checkpoints: api and manifest model for creating checkpoints

---

Cargo.lock
Cargo.toml
rfcs/0004-checkpoints.md
src/admin.rs
src/checkpoint.rs
src/cli/args.rs
src/cli/main.rs
src/db_state.rs
src/flatbuffer_types.rs

This patch adds CLI commands for creating, refreshing, deleting, and listing checkpoints:
- Adds public APIs for refreshing and deleting checkpoints.
- Adds CLI commands that are implemented by calling these public APIs.
- Updates the RFC with the public APIs for refreshing/deleting checkpoints.
Fixes #310
Checkpoints Milestone: https://github.com/slatedb/slatedb/issues/310

[2/N] checkpoints: add CLI commands for managing checkpoints

---

src/db.rs
src/db_common.rs
src/db_state.rs
src/error.rs
src/flush.rs
src/manifest_store.rs
src/mem_table_flush.rs
src/tablestore.rs

When a flush operation fails in the background, an error is populated in the COWDbState structure that handles the state of the database. Foreground operations check this error and returns it when the user tries to read or write from the database.
This is another improvement to handle errors described in #111.

fix(flush): Handle background flush errors.

---

.github/workflows/release.yaml
RELEASE.md

This PR adds a release.yaml Github action to make it easier to publish SlateDB releases. The action is triggered through the Github actions page. To run it, SlateDB committers input a version number and click "run workflow". The workflow will:
1. Verify that the version adheres to the semantic versioning format.
2. Check out the latest code from the `main` branch.
3. Update the version in Cargo.toml to the specified version.
4. Commit the changes and push to the `main` branch.
5. Create a Github release with the specified version and auto-generated release notes.
6. Publish a release to crates.io.
I've also added a RELEASE.md to describe this process.

Add release.yaml and RELEASE.md

---

Cargo.lock
Cargo.toml
src/admin.rs
src/bencher/benchmark-db.sh
src/cli/args.rs
src/cli/main.rs
src/config.rs
src/garbage_collector.rs

fixes #286
This PR introduces the ability to run GC on-demand and wires that mechanism into the admin CLI. The following changes were made to the public API:
- Changes the public API for `GarbageCollectorDirectoryOptions` by encapsulating the `poll_interval` in an enum
- Exposes two CLI methods. One to run a single one-off GC for a single resource type (Manifest/WAL/Compacted) and another to schedule a periodic GC job.
```
Runs a garbage collection for a specific resource type once
Usage: slatedb --path <PATH> run-garbage-collection --resource <RESOURCE> --min-age <MIN_AGE>
Options:
-r, --resource <RESOURCE>  If specified, the minimum age of manifests to collect [possible values: manifest, wal, compacted]
-m, --min-age <MIN_AGE>    If specified, the minimum age of manifests to collect
-h, …
```

support running GC from the admin CLI

---

.config/nextest.toml
.github/workflows/pr.yaml

The immediate motivation is configuring a per-test timeout in CI, but see https://nexte.st for the long list of improvements that cargo-nextest makes over cargo test.

Use cargo-nextest to run tests in CI

---

GOVERNANCE.md
MAINTAINERS.md
RELEASE.md

Adding a governance document based on [Vespa's](https://github.com/vespa-engine/vespa/blob/master/GOVERNANCE.md).
I tweaked the following things:
- Make all committers board members for now.
- Add reference to slatedb-pulumi for the official committer list.
- Cleaned some grammar.
- Added a carveout to allow committers to merge small PRs without approval.

Add a GOVERNANCE.md document

---

src/cached_object_store/object_store.rs
src/cli/main.rs
src/flatbuffer_types.rs
src/mem_table.rs
src/sst.rs

Clippy has started failing with a couple of silly issues. They added a `div_ceil` detector fairly recently, which is now complaining. It's also grumbling about unused lifetimes. Fixing those.

Remove unused lifetimes and use div_ceil in object storage cache

---

Cargo.lock
Cargo.toml
benches/db_operations.rs

(Creating as draft to get some feedback)
@dmvk detected a performance regression that's been discussed in #371 and #370. A small criterion test was created to illustrate the issue.
https://github.com/dmvk/slatedb-microbench/blob/0.2/Cargo.toml
In this PR, I'm:
- Adding `criterion` to SlateDB'
- Importing @dmvk's test into a `benches` directory
I ran the test locally on my laptop and got:
```
Running benches/db_operations.rs (target/release/deps/db_operations-1853152ecc617580)
put                     time:   [9.1050 µs 9.1298 µs 9.1607 µs]
Found 93 outliers among 1000 measurements (9.30%)
12 (1.20%) low severe
11 (1.10%) low mild
35 (3.50%) high mild
35 (3.50%) high severe
```
_#250 did some work to support Criterion and microbenchmarks, bet we haven't merged it yet. If we merge this, that …

Add a microbench bench test to detect performance regressions

---

src/admin.rs
src/checkpoint.rs
src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_state.rs
src/db.rs
src/error.rs
src/garbage_collector.rs
src/manifest_store.rs

Fixes #366. In addition to adding ID to `ManifestMissing`, this patch creates a separate error `LatestManifestMissing` when we are trying to find the latest and do not have a specific ID. This patch also adds a couple helpers for the common case when we expect either the latest manifest or a specific manifest to exist.

Add ID to ManifestMissing error

---

rfcs/0006-merge-operator.md

This is currently a draft, and there are a few points that I'd love to get input on.
In my view, the primary use case for the Merge Operator is buffering (essentially an append operation). However, the resulting list can become quite large in cases where there is per-key data skew. None of the existing implementations really address this, as they generally accept it as a fair limitation or memory constraint.
I'm considering extending the API to allow for limiting the size of merged values. In the case of an append operation, if the list grows beyond the defined limit, we could simply "close the batch" and start a new one. This would also improve performance of partial iterations.
Any thoughts?

RFC for MergeOperator.

---

.github/workflows/nightly.yaml
.github/workflows/pr.yaml
Cargo.toml

This PR adds a `cargo bench` that adds two new GH action jobs:
- Runs `cargo bench` whenever a PR is submitted
- Runs `carbo bench` nightly at 12AM Pacific
Both bench commands run the microbenchmarks in the `/benches` folder.
The PR check will leave a comment on the PR if the check resulted in a >= 200% slowdown, but it will not fail the PR. The PR check also will not save its results; it simply compares the most recent nightly's microbench data against the branch.
The nightly check behaves much like the PR check except that it saves the results using GH's `actions/cache` action, and the job will fail if there is a >= 200% slowdown.

Add `cargo bench` PR check and `bencher`nightly

---

.github/workflows/nightly.yaml
src/bencher/benchmark-db.sh

In #381, I added microbenchmarking checks to all PRs. I also added a nightly run that would set a new microbenchmark baseline.
This PR extends that work to add a nightly that runs the `benchmark-db.sh` script from #247. The new nightly job does the following:
- Runs `benchmark-db.sh`
- Pushes results to https://github.com/slatedb/slatedb-website's gh-pages branch under  the `performance/benchmarks/main` folder
- Fails if there is a >= 200% performance slowdown
- Caches results
To make all this work, I had to tweak `benchmark-db.sh` in a couple of places:
- Adds a `generate_json` method to generate a JSON file compatible with [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark)
- Makes `gnuplot` plot generation optional in `benchmark-db.sh`

Add `benchmark-db.sh` to nightly and publish results to the website

---

.github/workflows/nightly.yaml

Our `benchmark-db.sh` benchmark runs are failing right now because Github only provides 14GiB of space in its standard runners and we're using 16GiB. I took a look at upgrading to GH Teams in order to get us access to the large runners, but it's $4 per-seat. So, I opted to try out [Buildjet](https://buildjet.com/). I'm only enabling the image for our nightly `benchmark-db.sh` script. The microbenchmarks will continue to use a standard GH runner.
We might still want to migrate to actual AWS machines and an AWS GH runner, but in the meantime, this Buildjet will hopefully suffice.

Use Buildjet runner for nightly `benchmark-db.sh` performance test

---

.github/workflows/nightly.yaml

I've updated the `benchmark-db.sh` nightly job to print the GH runner's system info. I also tweaked it to use a non-/tmp directory to store its data since we're still running out of disk.

Print system info for perf tests and move data out of `/tmp`

---

.github/workflows/nightly.yaml

Buildjet was still running out of disk. The machines might be fast enough to fill quite a bit of disk. It appears Buildjet only has 64GB disk runners, so I'm switching to Warpbuild. Warpbuild also has the advantage of offering BYOC, which means we should be able to use it to provision AWS machines as well.

Ditch Buildjet for Warpbuild

---

.github/workflows/nightly.yaml
src/admin.rs
src/bencher/README.md
src/bencher/args.rs
src/bencher/benchmark-db.sh
src/bencher/main.rs

`bencher` now has a `--clean` argument that will delete all objects in the input path after the `bencher` subcommand runs. This switch works for both the compaction benchmarks and the db benchmarks.
By default, `--clean` is disabled since it's destructive. If `--clean` is set, `bencher` will check that the object store path is empty. If it is, it'll create a `.clean_benchmark_data` file, which will signal that the data should be deleted after the benchmark runs. If the path is not empty, the benchmark will fail. After the benchmark runs, if `--clean` is set and a `.clean_benchmark_data` exists, `bencher` will remove all objects from the path.

Add `--clean` option for `bencher`

---

.github/workflows/nightly.yaml

The `benchmarks` nightly job currently caches data using Github's cache. It turns out github-action-benchmark doesn't allow us to do this _and_ publish to our slatedb-website repo; it's either/or. So, I'm disabling the custom download/save caching jobs, and removing `external-data-json-path` so that the GH action simply uses the JSON data that's stored in the slatedb-website repo when saving and comparing old results.

Disable custom benchmark caching

---

src/db.rs
src/merge_iterator.rs
src/sst.rs
src/tablestore.rs
src/test_utils.rs
src/types.rs

This change also fixes correctness, because the original version was ignoring seq and create_ts from assertion.
Prerequisite for https://github.com/slatedb/slatedb/pull/391

Simplify test_utils::assert_iterator.

---

src/admin.rs
src/batch_write.rs
src/compactor.rs
src/db.rs
src/db_common.rs
src/db_state.rs
src/error.rs
src/flush.rs
src/garbage_collector.rs
src/lib.rs
src/mem_table.rs
src/mem_table_flush.rs
src/utils.rs

This patch tries to tighten up error handling to prevent writer clients from blocking indefinitely. Previously we could see:
- a writer could pass the initial error check and then write to the in memory table, and then block until the table is durable. meanwhile, the flush task could panic or become fenced and the writer would never be notified.
- a writer could block in the backpressure loop, which never clears because the compactor failed.
The approach here consists of the following changes:
First, we add some utility types/fns:
- `WriteOnceRegister` which represents a value that can be written once. Later writes are dropped. The type also supports waiting for a value to be written to the register.
- Utility methods for spawning monitored tasks and threads. A monitored task or thread is …

tighten up error handling to prevent writer clients from blocking indefinitely

---

src/sst.rs

- Add checksum to both filter and index block, and do checksum validation while decoding them. 
Fixes #365

Add checksum to filter and index block

---

README.md

I'm using this strategy to handle both light and dark themes:
https://www.stefanjudis.com/notes/how-to-define-dark-light-mode-images-in-github-markdown/
https://github.com/stefanjudis/github-light-dark-image-example
Looks to work well on Github. I'm not sure if it'll work on Crates.io, but I'm OK with that.

Brand SlateDB as a member of Commonhaus

---

src/db.rs

This makes `Db::open` play nice with `async_trait`.

Use `Arc` instead of `Rc` in `replay_wal`

---

src/db_iter.rs

This must have snuck in during development.
Followed `main/CONTRIBUTING.md`, the following were successful:
```
cargo clippy --all-targets --all-features
cargo fmt
cargo test --all-features
```

Remove unnecessary allow dead_code annotation

---

Cargo.lock
Cargo.toml
src/admin.rs

This PR updates the `object_store` crate to `0.11.2`, which contains this commit:
https://github.com/apache/arrow-rs/pull/6682
@benesch added S3 CAS support, which we can now take advantage of.
I removed a `warn!` in the `admin.rs` `load_aws` method since loading an AWS `ObjectStore` without a DynamoDB table should work now. I opted to leave support for DynamoDB intact in `admin.rs` since some users might wish to keep DynamoDB for other reasons.
Fixes #164

Upgrade `object_store` to support `put_if_not_exists` on S3 without DynamoDB

---

src/db.rs

I started noticing that `test_should_recover_imm_from_wal_after_flush_error` was failing sporadically when I was testing #418. Upon some investigation, it appears that this test has a race condition.
The test simulates a writer that fails after a write goes to the WAL but before it is written to L0. The test then creates a new DB client, which loads the WAL SSTs into a memtable table and freezes it using `replay_wal`. The problem appears to be that `maybe_freeze_memtable` in `replay_wal`:
https://github.com/slatedb/slatedb/blob/e87bc82cab78da2ac1759e53d3382fc104b6f64b/src/db.rs#L517
Freezes the memtable, which we want, but then it tells `mem_table_flush.rs` to flush the immutable memtable:
https://github.com/slatedb/slatedb/blob/e87bc82cab78da2ac1759e53d3382fc104b6f64b/src/db_common.rs#L18 …

Fix flaky `test_should_recover_imm_from_wal_after_flush_error` test

---

README.md

The README.md hasn't been updated since we now return results on `.await` calls. I added `.unwrap()`'s everywhere since it was most convenient.

Update `await` calls in README.md

---

src/config.rs

The docs specify that the default clock uses the current wallclock time in milliseconds, but the implementation uses seconds. This patch fixes the impl to use milliseconds

fix: use milliseconds for the system clock

---

src/compactor.rs
src/compactor_state.rs
src/db.rs
src/db_state.rs
src/mem_table_flush.rs

Fixes a bug found in https://github.com/slatedb/slatedb/pull/430 which causes checkpoints to get lost after the writer updates the manifest. Since checkpoints are added externally, we need to merge them into the writer's state. I've also changed the name `refresh_db_state` to `merge_db_state` since I think that reflects the usage a bit more clearly.

Writer should merge added checkpoints into its db state

---

src/compactor_state.rs

Similar to #435. The compactor also needs to account for newly added checkpoints.
Worth noting that @rodesai and I have been discussing a more robust solution in which the writer and compactor can record their changes in some kind of Delta struct and then apply them on top of the latest state. I've opened https://github.com/slatedb/slatedb/issues/436 for this potential improvement.

Compactor should account for checkpoints when merging manifest state

---

src/batch_write.rs
src/db_iter.rs
src/mem_table.rs
src/tablestore.rs

See #434 for context on reducing log level

MINOR: reduce log level on clean shutdown and fix clippy warns

---

src/lib.rs

Currently users are expected to access metrics by calling `Db::metrics` which returns an `Arc<DbStats>`. `DbStats` is publicly visible, but the containing module `metrics` is not, so users cannot actually access the statistics. This patch changes the visibility of `metrics` to `pub`

make metrics publicly visible

---

src/db.rs

When the wal is disabled, `Db.flush` currently writes only the memtables that are awaiting flush.  We also need to rotate the current memtable so that the latest writes are persisted as well.

Freeze current memtable when flushing with wal disabled

---

src/db.rs
src/db_state.rs
src/flush.rs
src/mem_table.rs

I found `next_wal_sst_id` to be overloaded. It currently seems to represent two things:
- The last WAL SST ID that was written (as `next_wal_sst_id - 1`)
- The next WAL SST ID to use when creating an immutable WAL (that hasn't yet been written)
After discussing with @agavra, it seems like the simplest thing to do was to remove ID from `ImmutableWal`, and read/update the `next_wal_sst_id` in `flush.rs` when the write actually occurs. Changes include:
- Keeps the previous test I wrote
- Removes `id` from `ImmutableWal`
- Uses `next_wal_sst_id` in `flush.rs` to determine the next WAL SST ID to use
- Increments `next_wal_sst_id` via (`increment_next_wal_id`) upon a successful WAL write
Fixes #433

Fix `wal_id_last_seen` race condition

---

schemas/manifest.fbs
src/batch_write.rs
src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_state.rs
src/db.rs
src/db_state.rs
src/flatbuffer_types.rs
src/generated/manifest_generated.rs
src/manifest_store.rs
src/mem_table.rs
src/mem_table_flush.rs
src/size_tiered_compaction.rs
src/utils.rs

fixes #431 - the clock tick in the manifest will be valid up until `wal_id_last_seen` however restore will attempt to update the clock tick even for wals earlier than `wal_id_last_seen`, which causes the symptoms in #431
The fix here makes a few changes:
1. the db state (manifest) last clock tick is only updated when either a WAL is flushed (wal enabled) or the memtable is flushed to L0 (wal disabled)
2. recovery no longer updates the db state last clock tick, but instead updates the internal clock's "last tick"
3. wraps the user-supplied `DbOptions` with `DbConfig` which allows us to create internally managed objects, such as `MonotonicClock` which is introduced in this PR
4. The `MonotonicClock` is initialized when loading the DB from the manifest/WALs

fix issue with clock tick recovery reading from WAL

---

src/error.rs
src/lib.rs
src/merge_operator.rs
src/types.rs
src/utils.rs

Depends on https://github.com/slatedb/slatedb/pull/336
This PR adds a generic KVIterator wrapper that transparently merges merge operands. Usage of the new iterator will come in separate PR.

2/N Merge Operator Iterator

---

rfcs/0004-checkpoints.md
src/admin.rs
src/checkpoint.rs
src/cli/main.rs
src/config.rs
src/db.rs
src/db_common.rs
src/db_state.rs
src/error.rs
src/flush.rs
src/manifest_store.rs
src/mem_table_flush.rs
src/test_utils.rs
src/utils.rs

Implement new instance `Db::create_checkpoint` specified in [RFC-0004](https://github.com/slatedb/slatedb/blob/main/rfcs/0004-checkpoints.md) which allows users control over the checkpoint scope.

Logic for creating checkpoints with control over scope

---

src/db.rs
src/db_common.rs
src/flush.rs

We ended up refactoring the memtable flusher so that it no longer uses `FlushMsg`. This patch makes a similar transformation for the wal flush msg for simpler and more consistent usage.

MINOR: Refactor wal flush msg for consistent pattern

---

src/checkpoint.rs
src/manifest_store.rs
src/mem_table_flush.rs

Follow-up for https://github.com/slatedb/slatedb/pull/443/files. We were left with two separate paths for checkpoint creation with slightly inconsistent behavior. For one, we used a different error when the source checkpoint could not be found. Additionally, when no source manifest was provided, we used the current manifest ID through one path and the next manifest ID through the other. This patch consolidates the two paths so that they use the same function to construct the checkpoint object.

Consolidate checkpoint creation logic

---

src/bytes_generator.rs
src/compaction_execute_bench.rs
src/lib.rs
src/sorted_run_iterator.rs
src/sst_iter.rs

This PR renames `bytes.rs` to `bytes_generator.rs` so that we can re-export the `bytes` crate without a name conflict. This is to lay the groundwork for #450, where we've decided we want to keep `Bytes` as the return type for our API. To make life easier on users, I think we should re-export the `bytes` crate since we're using it in our public API (like we do with the `object_store` and `fail_parallel` crates).
I considered deleting `bytes.rs` and moving its content into `test_utils.rs`, but `OrderedBytesGenerator` is used by the `bencher` feature, which is a feature flag, not a test. When importing `test_utils` for `bencher`, it was causing a bunch of "unused" errors because of all the test functions that weren't used.
I also considered trying to use `extern` to somehow alias the `bytes` …

Rename `bytes.rs` and re-export `bytes` crate

---

src/lib.rs
src/types.rs

This patch makes KeyValue visible by making the types module pub. The types module also contains a bunch of internal types, so these have all been changed to pub(crate)

make KeyValue visible so users of scan can access it

---

src/garbage_collector.rs
src/lib.rs
src/paths.rs
src/tablestore.rs

Pull logic for building and parsing paths into a separate `PathResolver`. This is more convenient in contexts where we may not need a tablestore.

Factor out path resolver

---

benches/db_operations.rs
src/batch.rs
src/bencher/args.rs
src/bencher/db.rs
src/bencher/main.rs
src/checkpoint.rs
src/cli/main.rs
src/config.rs
src/db_cache/mod.rs
src/error.rs
src/lib.rs
src/merge_operator.rs
src/metrics.rs

This patch makes a couple of changes to the way public names are exported:
- It exports many of the public names at the top level of the crate (e.g. lib.rs) to avoid leaking the internal module structure. I retained a few public modules for cases where I think it makes sense to expose the contained names within a module because the components should be grouped (e.g. configs, metrics, pluggable stuff like the dbcache)
- It adds non_exhaustive to all enums to force any users matching on the enums to include wildcards in case new variants are added.
- Adds non_exhaustive to all pub structs with all pub fields that are constructed by calling into a fn exported by slatedb to prevent users from constructing these directly. In the case that the struct contains a private or pub(crate) field we …

restructure exports to top level of crate

---

.github/workflows/pr.yaml
README.md
src/db.rs
src/db_cache/foyer.rs
src/db_cache/moka.rs

Some of the doc examples were broken in https://github.com/slatedb/slatedb/pull/463. This patch fixes them.

Fix doc tests broken by pub use changes

---

src/blob.rs
src/sst.rs
src/tablestore.rs

Arrow's `ObjectStore` crate has changed their `Range` and `usize` lengths to `u64`. This will break SlateDB when we upgrade to the latest version.
While investigating what needs to change on our end, I noticed that we use a `u32` for our metadata offset in SSTs. This offset is at the tail end of each SST file and describes where to seek to in order to get index and filter data.
Using a `u32` for the metadata offset means we can't have an SST larger than ~4GiB. After some discussion on Discord, we decided it's worth supporting larger SSTs as well. To make this change, I've:
- Changed the SST's current_len to be `u64`
- Updated `read_info` to read 8 bytes for the metadata offset
- Updated filter and index offsets to use `u64` throughout
- Updated `ReadOnlyBlob` to use u64 for read range and …

Use `u64` for SST metadata offset to support big SSTs

---

src/batch_write.rs
src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_executor.rs
src/compactor_state.rs
src/db.rs
src/flush.rs
src/garbage_collector.rs
src/mem_table_flush.rs
src/utils.rs

This patch makes a few changes to ensure we cleanup compaction jobs when they fail:
- We now track compaction jobs by a unique id rather than the destination. Though this is not strictly required, it feels a bit safer as a way to correlate msgs from the executor with the compactor's state.
- When a compaction fails, the executor's message includes both the id and the error.
- The compactor orchestrator clears the compaction job from its state when a compaction fails.
- Changes the executor to use a monitored background task for compaction, and to send the orchestrator the result from the task's cleanup fn. This way we also report failures due to a compaction panic'ing. This also required changing the cleanup fn to take a Result rather than just an error, and updating the existing cleanup …

fix: cleanup compaction job on failure

---

src/compactor.rs
src/manifest_store.rs

This patch changes the compaction orchestrator to leave behind a temporary (15-minute) checkpoint when it writes a new manifest after finishing a compaction. This avoids a race condition like:
1. compactor writes a new manifest that removes SST X
2. gc deletes SST X because it was created a long time ago
3. writer tries to read SST X because it hasn't refreshed its manifest yet
Step 1 for fixing #204

fix: leave behind a checkpoint when writing manifest from compactor

---

src/bytes_generator.rs
src/db.rs
src/db_cache/foyer.rs
src/db_cache/mod.rs
src/db_cache/moka.rs
src/lib.rs
src/sst.rs
src/tablestore.rs
src/test_utils.rs

This patch adds some stats about block cache accesses and usage. The stats are measured and reported in a way that works when the cache is shared between multiple slatedb instances:
- The stats are added to a separate struct (DbCacheStats) from the main DbStats struct.
- The stats are measured via a wrapper of the main cache backend arc called DbCacheWrapper. This patch changes the type that's passed into the config and stored in the TableStore to DbCacheWrapper. Users now need to create a DbCacheWrapper instance from the Arc<dyn DbCache> if they want to provide a specific cache implementation.
- The stats can be accessed via the stats fn in DbCacheWrapper. So users that pass a single DbCacheWrapper instance to multiple SlateDBs can get aggregated stats for the cache.

add stats about block cache hits/misses and usage

---

src/block.rs
src/db_cache/mod.rs
src/filter.rs
src/flatbuffer_types.rs
src/utils.rs

This patch changes the cache wrapper to clamp buffers backing entries to the block cache to the minimally sized buffer required.
Normally, the buffer backing an entry may be significantly larger than the entry itself:
- some entries (like data blocks) internally contain slices that point to a larger buffer that was used to fetch a larger chunk of data (e.g. in the data block example, a scan will read a range of blocks and hand each block a slice)
- even entries derived from reads of just the relevant data (like indexes and filters) may contain larger backing buffers due to the behaviour of dynamically sized buffer data structures like Vec, which allocate the data by doubling it when required to achieve amortized O(1) updates.
Consequently, the block cache may think that it's cached some …

fix: clamp the buffers backing entries inserted to the block cache

---

src/checkpoint.rs
src/clone.rs
src/compactor.rs
src/compactor_state.rs
src/db.rs
src/db_state.rs
src/flush.rs
src/garbage_collector.rs
src/manifest/store.rs
src/mem_table_flush.rs
src/size_tiered_compaction.rs

This patch refactors the manifest store by changing the way that manifests are updated. To update a manifest you now call prepare_dirty, which returns an instance of DirtyManifest. DirtyManifest contains the manifest contents, along with its id, and the id that it will be written with (next_id). You then make changes to the dirty manifest, and pass it to update_manifest. update_manifest verifies that next_id matches the expected next id before writing out the dirty manifest.
DbState/CompactorState now work by storing a DirtyManifest with the local changes, rather than just CoreDbState, and the db/compactor use this dirty manifest when updating the manifest.
This change confers two benefits:
Firstly, and the primary goal of this patch, it makes manifest updates safer by reducing the …

write manifests more safely by verifying the expected next id

---

src/checkpoint.rs
src/compactor.rs
src/config.rs
src/db.rs
src/flush.rs

This makes the flush loop optional. I haven't added any new tests, but I have confirmed that existing tests pass.

Make flush_interval optional (#505)

---

src/comparable_range.rs
src/lib.rs

This is a prerequisite for supporting projections / unions. It also aims to simplify code around handling of byte_ranges, which will be done in separate PR.
This seems well scoped enough to be separate PR, https://github.com/slatedb/slatedb/pull/493 builds on top of this.

Add ComparableRange module.

---

src/error.rs
src/flatbuffer_types.rs
src/sst.rs

This PR adds very rudimentary version number handling for SSTs and manifests. My main goal is simply to get the version bytes in the right spot, so we can implement proper version handling going forward. The most important part of this PR are the byte sizes and locations in the byte formats.
Changes:
- Adds a u16 to the _end_ of an SST's on-disk byte format
- Adds a u16 to the _beginning_ of a manifest's on-disk byte format
- Adds version validation logic in `FlatBufferManifestCodec::decode`
- Adds version validation logic in `SsTableFormat::read_info`
- Adds an `InvalidVersion` error
- Adds tests for validation logic
A couple of notes/oddities:
- I opted to put the encode/decode logic inside the manifest's flat buffer codec because we don't currently have an intermediate builder for it …

Add version bytes for SST and manifest byte formats

---

src/db.rs
src/sst_iter.rs

This patch fixes the SstIterator's index search path to correctly handle SSTs where multiple blocks contain the same starting key (which is now possible in l0 since we store multiple key versions in the memtable). The fix is to not terminate the binary search of the block metas when a match is found - but rather to keep looking for a lower-indexed block.
fixes #517

fix: handle repeated keys during sst index search

---

src/flatbuffer_types.rs
src/lib.rs
src/partitioned_keyspace.rs
src/sst_iter.rs

This patch fixes two issues with selecting the start and end blocks for an sst iterator:
- for the start block, in the case where iteration starts from the same key as the first key in a block B, we were selecting B as the start block. Instead, if B > 0 we should start from B-1 because block B-1 may end with the specified key.
- for the last block, we were selecting the block after the start block. After fixing the above bug, in the case where a key first appears as the first key in some block B, we wind up excluding B because the search spans [B-1,B).
This patch makes a few changes to fix these problems:
- It adds a trait called RangePartitionedKeySpace that defines a key space that is split up into a list of partitions, each of which has a first key. We need this trait because we can't …

fix block filtering when creating sst iterator

---

Cargo.lock
Cargo.toml
src/block.rs
src/db_cache/mod.rs
src/db_cache/serde.rs
src/flatbuffer_types.rs

This patch implements Serialize/Deserialize for CachedKey/CachedEntry so that we can then support db cache impls that write cache entries to local disk. The impls work by first converting CachedKey and CachedEntry to/from types that #[derive] Serialize/Deserialize. This way the in-memory representations are decoupled from the on-disk format.

Add Serialize/Deserialize impls for CachedKey/CachedEntry

---

Cargo.lock
Cargo.toml
src/db_cache/foyer.rs
src/db_cache/foyer_hybrid.rs
src/db_cache/mod.rs
src/db_cache/moka.rs
src/error.rs
src/tablestore.rs

This patch adds an implementation of `DbCache` that uses a foyer hybrid cache to store cached blocks on-disk as well as in-memory. `FoyerHybridCache` can fail gets, so this patch also changes `DbCache` to support returning errors. Currently errors are handled as follows:
- tablestore just ignores errors and treats them as cache misses
- `DbCacheWrapper` tracks a counter of errors, and logs them. The log is rate-limited to once per second (so as not to spam logs on non-transient errors like out-of-disk).

add a dbcache impl that uses the foyer hybrid cache

---

src/config.rs
src/db.rs
src/db_reader.rs
src/reader.rs
src/utils.rs

This patch changes the current ReadLevel and ReadOptions.read_level to DurabilityLevel and ReadOptions.durability_filter as described in RFC-8. It also changes the read path when wal is disabled to respect the durability filter by only reading from the memtable if the durability_filter is set to Memory. Previously we were disregarding the read level when wal was disabled.

change read level to durability filter

---

src/store_provider.rs

StoreProvider needs to be Send+Sync for the future returned by DbReader::open to be Send. Without this you can't use DbReader from something that impls a trait using async_trait

make StoreProvider Send+Sync

---

src/block_iterator.rs
src/filter_iterator.rs
src/iter.rs
src/mem_table.rs
src/merge_iterator.rs
src/merge_operator.rs
src/sorted_run_iterator.rs
src/sst_iter.rs
src/test_utils.rs

currently `MergeIterator` has a limitation: all the iterators passed to it has to be the same type.
i tried passing a `Box<dyn KeyValueIterator>` to it, but rust type system fails that `KeyValueIterator` is not able to be used as trait object.
```
--> src/merge_iterator.rs:150:13
|
150 |     it: Box<dyn KeyValueIterator>,
|             ^^^^^^^^^^^^^^^^^^^^ `KeyValueIterator` cannot be made into an object
|
note: for a trait to be "dyn-compatible" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
--> src/iter.rs:18:14
|
16  | pub trait KeyValueIterator {
|           ---------------- this trait cannot be made into an object...
17  |     /// Returns the next …
```

chore: wrap async-trait to KeyValueIterator & SeekToKey

---

src/db.rs
src/db_reader.rs
src/filter_iterator.rs
src/mem_table.rs
src/reader.rs

`get()` and `scan()` runs different code path. besides adding `max_seq` for `scan()` in #536, it's also needed to have the `max_seq` filter in `get()`.
(we can consider add some proptest that checks that `get()` should always return the exactly the same result as `scan().next_entry()` in the next change)
this pr still needs some test cases.
this pr is also related with #489.

refactor(reader.rs): add a LevelGet struct that filter max_seq in get() and tests with expire_ts handling

---

rust-toolchain.toml
src/bencher/main.rs
src/cached_object_store/storage_fs.rs
src/clone.rs
src/db.rs
src/error.rs
src/filter.rs
src/lib.rs
src/tablestore.rs

recent PRs have failed on clippy several times, but I cannot reproduce the clippy error locally without upgrading my local rust toolchain.
it seems the github workflow may upgrade the rust toolchain randomly.
this PR adds a rust-toolchain.toml file to ensure the consistency between workflow and local, and fix the clippy errors.

chore: fix clippy; add rust-toolchain.toml

---

src/block_iterator.rs
src/compactor_executor.rs
src/db_iter.rs
src/error.rs
src/filter_iterator.rs
src/iter.rs
src/mem_table.rs
src/merge_iterator.rs
src/merge_operator.rs
src/sorted_run_iterator.rs
src/sst_iter.rs
src/test_utils.rs

currently there's a limitation in `MergeIterator`: the children iterator passed to it has to be the same type.
this pr makes KeyValueIterator able to be used as a trait object, so we can pass different implementations of `KeyValueIterator` into it.
Rust type system does not allow things like `Box<dyn KeyValueIterator + SeekToKey>`, so this pr has to merge the trait `SeekToKey` into `KeyValueIterator` together.

refactor: let MergeIterator accepts Box<dyn KeyValueIterator>; merge SeekToKey into KeyValueIterator

---

src/db.rs
src/reader.rs

Before this patch, if you tried to use DbIterator behind a Box<dyn> you would get build errors complaining about the lifetime associated with the closure used to generate the memtable iterators. This is a pretty common use case where a user may want to abstract away the underlying storage engine from the rest of their application. I think the error is because of the extra constraints introduced by async_trait. To fix this, we collect the iterators into a Vec before passing them to MergeIterator. 
The patch also includes a test that replicates the error. Before the fix, the test case fails to build with:
```
error: implementation of `FnOnce` is not general enough
--> src/db.rs:1816:76
|
1816 |               async fn iterator<'a>(&'a self) -> Box<dyn IteratorTrait + 'a> {
| …
```

fix: fix build error when using dbiterator behind a Box<dyn>

---

src/db.rs
src/flush.rs

I noticed that setting `flush_interval` as `None` currently does not work. If it's set as `None`, currently the flush task just stops:
https://github.com/slatedb/slatedb/blob/9e4a80b37fd91cd29b7a485712ea3cb2ba7388f8/src/flush.rs#L101-L104
However this task not only performs periodic flushes, it also handles manual flush requests (which don't work in this case):
https://github.com/slatedb/slatedb/blob/9e4a80b37fd91cd29b7a485712ea3cb2ba7388f8/src/flush.rs#L128-L129
When `flush_interval` is `None`, change the behavior to start the flush task- just without the periodic ticking.
The test I added in `db.rs` fails without the code change in `flush.rs`:
```
$ git restore --source=HEAD^ src/flush.rs
$ cargo test  test_no_flush_interval
Finished `test` profile [unoptimized + debuginfo] target(s) in …
```

[bug] db_options.flush_interval=None broken

---

src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_executor.rs
src/types.rs

This PR will close #285
Unfortunately I didn't come up with a good way to add unit tests, because tombstones behave the same when accessed via the `Get` operation regardless of whether they're physically removed or not.
I followed @rodesai suggestion of letting the orchestrator decide whether the dest sorted run is the last sorted run or not.

fix(compaction): filter tombstones out when compacting into the last sorted run

---

src/db.rs

I added a test based on the bug report from #555. The test successfully replicated the issue on tag v0.6.1, but appears to have already been fixed on main. I didn't dig into why. Perhaps it's related to #548. In any case, I want to include a test just to make sure we don't hit the issue again in the future.
Fixes #555

Verify that compression works without panics

---

src/db.rs

The header file has already referenced this header file. I personally feel that there is no need to reference it again.

chore: Remove duplicate references

---

rfcs/0010-settings-vs-components.md

Hi folks 👋 
I was reading some of the latest changes in SlateDB and I wanted to bring forward a proposal to be more intentional about how to configure the engine.
When I implemented the [ability to load settings from plain text files](https://github.com/slatedb/slatedb/pull/270) I noticed that the `DbOptions` struct has a mix of settings that a user can configure via text, and components that the database uses for different things, like the `gc_runtime`.
#533 adds a new component that instead of being in `DBOptions`, is passed to the `open_with_opts` functions directly.
It's starting to sound to me like there is no clear pattern for adding settings and configurable components that makes it easy to keep future and past compatibility stable.
I wrote a proposal to improve this situation with …

RFC: Settings vs components

---

schemas/manifest.fbs
src/mem_table.rs

this PR adds brief descriptions for two fields related to WAL replays during the recovery phase.

chore: add comment about last_wal_id and wal_id_last_compacted

---

src/mem_table.rs

1. Add meetable track last_seq test
2. Delete duplicate test examples

chore: Add memtable track last_seq test

---

src/compactor.rs
src/mem_table_flush.rs

The shutdown messages for the memtable flusher are a little scary. I've updated them to be a WARN and imply that the manifest update is retrying.
Fixes #566

Make shutdown manifest conflict logs less scary

---

slatedb/src/db.rs
slatedb/src/sst.rs

This PR fixes a bug in how we compress blocks. Before the fix, we were compressing the entire block _after_ it was encoded. This means that we should decompress the entire block _before_ it's decoded. Unfortunately, we were not. Instead, we were calling `Block::decode` and _then_ calling decompress. This will of course give the wrong bytes to the decode method. As a result, we were seeing a subtraction overflow because we were getting random (compressed) bytes for the `entry_offsets_len` in the Block::decode method.
I've fixed this issue by decompressing the block bytes _before_ they're decoded.
Fixes #555

Decompress block bytes before decoding

---

.github/workflows/nightly.yaml

It looks like #554 missed a couple of spots in the Github nightly.yaml file. This PR fixes two issues:
- The bencher job was referring to `src/`, which was removed in the above PR.
- The pprof job caught the new slatedb-cli package as part of its list of potential microbenchmarks to run.
I've updated the path and changed the pprof commands to filter out all non-"bench" kinds.

Fixing nightly perf tests

---

Cargo.lock
slatedb/Cargo.toml

Upgrade foyer to v0.17.2 for fast recovery and other new features and bug fixes.
cc @rodesai Please feel free to try this version to see how recovery goes.

chore(deps): upgrade foyer to v0.17.2

---

schemas/manifest.fbs
slatedb/src/admin.rs
slatedb/src/checkpoint.rs
slatedb/src/clone.rs
slatedb/src/compaction_execute_bench.rs
slatedb/src/compactor.rs
slatedb/src/compactor_state.rs
slatedb/src/db.rs
slatedb/src/db/builder.rs
slatedb/src/db_reader.rs
slatedb/src/db_state.rs
slatedb/src/flatbuffer_types.rs
slatedb/src/garbage_collector.rs
slatedb/src/generated/manifest_generated.rs
slatedb/src/lib.rs
slatedb/src/manifest/store.rs
slatedb/src/object_stores.rs
slatedb/src/reader.rs
slatedb/src/size_tiered_compaction.rs
slatedb/src/sorted_run_iterator.rs
slatedb/src/sst.rs
slatedb/src/sst_iter.rs
slatedb/src/store_provider.rs
slatedb/src/tablestore.rs
slatedb/src/wal_replay.rs

This PR is the first in the series and introduces the following:
- Configuration support via `DbBuilder`.
- `TableStore` now selects an appropriate object store based on a `SsTableId`.
- `Manifest(V1)` now contains `wal_object_store_uri`, currently serving just as
a flag.

Initial support for separate WAL object store

---

Cargo.lock
slatedb-cli/Cargo.toml
slatedb-cli/src/main.rs
slatedb/Cargo.toml
slatedb/src/admin.rs
slatedb/src/config.rs
slatedb/src/db.rs
slatedb/src/db/builder.rs
slatedb/src/garbage_collector.rs
slatedb/src/garbage_collector/compacted_gc.rs
slatedb/src/garbage_collector/manifest_gc.rs
slatedb/src/garbage_collector/stats.rs
slatedb/src/garbage_collector/wal_gc.rs

Introduce a simplified version of the GarbageCollector that doesn't use crossbeam::channels for concurrency control.
This new implementation also removes the state machine that made the code more complex in favor of purposely defined functions. This fixes some fleaky tests that could crash because the GC thread terminated ahead of time and made the database enter an error state.
This change also asumes that the admin tools don't run in the same process than the actual database, hence there is no need of a fully dedicated system thread to run the garbage collector, it can run in a Tokio task. The caller can decide to run the task in a separated system thread if it's necessary for the task at hand.
Fixes #380 
NOTE: GitHub collapses the garbage_collector.rs file, be sure to review it …

fix(gc): Reimplement the garbage collector without crossbeam.

---

Cargo.lock
slatedb/Cargo.toml
slatedb/src/cached_object_store/storage_fs.rs
slatedb/src/checkpoint.rs
slatedb/src/clone.rs
slatedb/src/compaction_execute_bench.rs
slatedb/src/compactor_executor.rs
slatedb/src/compactor_state.rs
slatedb/src/db/builder.rs
slatedb/src/db_reader.rs
slatedb/src/db_state.rs
slatedb/src/flatbuffer_types.rs
slatedb/src/garbage_collector.rs
slatedb/src/lib.rs
slatedb/src/manifest/mod.rs
slatedb/src/manifest/store.rs
slatedb/src/mem_table_flush.rs
slatedb/src/object_stores.rs
slatedb/src/rand.rs
slatedb/src/size_tiered_compaction.rs
slatedb/src/sorted_run_iterator.rs
slatedb/src/tablestore.rs
slatedb/src/utils.rs

This PR:
* Introduces a new internal `slatedb::rand` module that encapsulates all random-number generation using `Xoshiro128PlusPlus`. I chose `Xoshiro128PlusPlus` because I wanted a PRNG that was portable across operating systems (so we can reproduce GH action failures locally). The standard `rand` PRNG's aren't portable. I didn't go with `ChaCha` because `Xoshiro128PlusPlus` is faster and we don't need cryptographically secure RNG.
* Replaces every direct call to `rand::thread_rng()`, `Ulid::new()`, and `Uuid::new_v4()` (including in tests) with the new helpers:
* `crate::rand::thread_rng()`
* `crate::utils::ulid()`
* `crate::utils::uuid()`
* Adds a `DbBuilder::with_seed(u64)` method so users can configure a global seed for fully deterministic behavior.
* Bumps dependencies to pull in …

Centralize RNG logic and add deterministic seeding support

---

.github/workflows/release.yaml
RELEASE.md

Allow running publish from a branch to allow patch releases after main has advanced. Publish will now check out the branch that the workflow was run against. This will allow us to create a branch like "0.6.x" from the initial 0.6.0 release tag, and then do future patch releases from that branch so that we can continue to patch release even after main has advanced and included potentially breaking changes.

support patch releases after main has advanced

---

slatedb/src/compactor.rs
slatedb/src/compactor_executor.rs

While debugging #595 and its subsequent [GH action failure](https://github.com/slatedb/slatedb/actions/runs/15473197912/job/43562555846), I noticed the other compactor tests were failing sporadically. They were, on occasion, hanging. I added multiple threads for the tests, and they no longer seem to hang.
I don't think this bodes well. I worry there might be some lock that's getting held on to. Things should make progress even on a single async runtime thread. Anyway, we're getting close to DST with #267. When we do DST, we'll be running on one thread, and I expect we'll be able to suss this out.
Separately, I also want to note that the GH action failure was not because of a timeout. We saw this instead:
```
--- STDOUT:              slatedb compactor::tests::test_compactor_compacts_l0 --- …
```

Fix race condition in compaction executor

---

slatedb-cli/src/main.rs
slatedb/clippy.toml
slatedb/src/admin.rs
slatedb/src/cached_object_store/object_store.rs
slatedb/src/cached_object_store/storage_fs.rs
slatedb/src/checkpoint.rs
slatedb/src/clock.rs
slatedb/src/compaction_execute_bench.rs
slatedb/src/compactor.rs
slatedb/src/compactor_state.rs
slatedb/src/db.rs
slatedb/src/db/builder.rs
slatedb/src/db_cache/mod.rs
slatedb/src/db_cache/moka.rs
slatedb/src/db_reader.rs
slatedb/src/db_state.rs
slatedb/src/garbage_collector.rs
slatedb/src/manifest/store.rs
slatedb/src/reader.rs
slatedb/src/test_utils.rs
slatedb/src/utils.rs

This PR updates SlateDB to use `SystemTime` instead of the typical `std` system clock. It's part of the work for #267.
The following changes usages of SystemTime have been updated:
- Moved `MonotonicClock` into `clock.rs`
- Made `clippy.toml` detect `std::time`, `uuid`, and `ulid` usage
- checkpoint.rs uses SystemTime::now()
- config.rs's SystemClock, which is used for TTL and checkpoint times.
- CompactorEventHandler::finish_compaction uses SystemTime::now() for logging last compaction timestamp in stats.
- db_cache/mod.rs uses Instant::now() when setting last_err_log_instant
- garbage_collector.rs uses Utc::now() in run_gc_task.
- storage_fs.rs::background_evict uses SystemTime::now()
I could not update the following two usages:
1. In moka.rs if ttl or tti are set. (Note: it appears …

Use `SystemClock` instead of `std::time`

---

slatedb/src/db.rs

This test was failing sporadically after #608 was merged. The issue appears to be that the WAL flush can call `maybe_memtable_flush`. This method will send a message to `mem_table_flush.rs` to flush any memtables. If this message arrives and the memtable gets flushed _before_ the fence happens in the test, then the subsequent `db1.inner.flush_memtables` will pass because there's nothing in the memtable. I added fail points to force the memtable not to flush until after the fence happens.

Fix `test_memtable_flush_cleanup_when_fenced` so it doesn't fail

---

slatedb/src/admin.rs
slatedb/src/compaction_execute_bench.rs
slatedb/src/compactor.rs
slatedb/src/compactor_executor.rs
slatedb/src/compactor_state.rs
slatedb/src/db.rs
slatedb/src/db/builder.rs
slatedb/src/garbage_collector.rs
slatedb/src/size_tiered_compaction.rs
slatedb/src/test_utils.rs

This is the next DST PR after #613. The compactor was originally a mixture of sync and async code. The event loop was synchronous and ran in a thread. This differs from the GC, which has an async event loop. This PR unifies the design of the compactor and the garbage collector. My hope is that this will make it easier for us to do DST since we can have the compactor run on the same single threaded tokio runtime as everything else.
- Replace crossbeam with tokio
- Remove `CompactorOrchestator` (it seemed like an unneeded layer of abstraction)
- Replace the thread in `Compactor::new` with `start_async_task` and `start_in_bg_thread`
- Add `CompactorBuilder` to `builder.rs`
- Get rid of err_*x and replace `CompactorMainMsg` with a `CancellationToken`
- Update a bunch of tests
Notes:
1. I …

Add `CompactorBuilder` and make `Compactor` async

---

slatedb/src/config.rs
slatedb/src/db.rs
slatedb/src/wal_buffer.rs

this is another try of having fatal state to get propogated when wal flushing got unrecoverable error.
this `handle_fatal` is kinda ugly, i suppose another way is directly expose `db.state.error` to underlying components like `WalBufferManager`, as it can be considered as a globally coordinated primitive, instead of an inner state of db state.

fix(wal): track db fatal when wal flusher got unrecoverable error

---

.gitignore
slatedb-py/python/slatedb/slatedb.pyi
slatedb-py/src/lib.rs
slatedb-py/tests/test_basic_operations.py

Added the scan function, as the iterator pattern was too difficult to write, a simple version was implemented first.
Added put_xxx, get_xxx, etc., functions to simplify usage.
@calavera please review

Add more functions to the Python binding

---

slatedb/src/compactor.rs
slatedb/src/error.rs

While working on #640, I found the compactor fails when stop() is called. I introduced the issue when I made the compactor async in #620. `Compactor`'s event loop (async) calls `CompactorEventHandler`'s `stop_executor`. The call stack eventually reaches `CompactionExecutor`'s `stop()` method. Everything from the `stop_executor` call on down is sync. Then, in `stop()`, I had the `TokioCompactionExecutor `'s `stop()` method call `this.handle.spawn_blocking()`. Tokio doesn't allow this because, though `stop()` is sync, it detects it's inside another runtime (the `Compactor`'s).
I fixed the issue by making the remaining `CompactorEventHandler` functions async (minus a couple of little helpers). This is mostly for clarity since it seemed to call `spawn_blocking` on our own …

Insulate compactor from executor async runtimes

---

slatedb/clippy.toml
slatedb/src/admin.rs
slatedb/src/compactor.rs
slatedb/src/db.rs
slatedb/src/db/builder.rs
slatedb/src/garbage_collector.rs
slatedb/src/utils.rs

This is a fast follow-on for #620. While making the `Compactor` async, I noticed that some improvements could be made to the GC:
- Update `Db` to use `garbage_collector_task` rather than `GarbageCollector`
- Update `DbBuilder` to use `spawn_bg_task` for the GC
- Remove unused `spawn_bg_thread` in `utils.rs`
- Detect thread usage now that we're fully async
- Update some docs
I opted not to add a `garbage_collector_runtime` param to `run_async_task`. The current behavior remains as it was: the GC event loop and GcTasks both run on the same GC runtime. I started down that path, but it felt like overkill. If a GC goes slow, I think it's far less consequential than a slow compactor. We can always add it later if we deem it necessary.

Remove `GarbageCollector::start_in_bg_thread`

---

slatedb/src/db.rs
slatedb/src/db/builder.rs

I noticed that we're still using `cache_blocks` in `replay_wal`. This will cache the WAL's blocks in the in-memory block cache. Since #519, we don't read from the WAL anymore (except during replay). Caching its blocks during WAL replay is useless.
Fixes #646

Disable cache for WAL replay iterator

---

slatedb/src/db.rs

related: #647
this pr uses explicit options on write options and read options, to test over the case about a `get()` should always get the committed data with `dirty: false`. 
(currently the `sync` field is not supported yet. all the writes' sync level are considered as memory, this should be added in a pr).

test: let test_get_after_put to use explicit options instead of defaults

---

slatedb/Cargo.toml
slatedb/src/config.rs
slatedb/src/tablestore.rs

@Barre discovered that Moka could get into a ton of contention under his workload. It's not immediately apparent what the issue is with Moka, but switching to Foyer fixed the problem immediately.
@Barre also discovered that the 1GiB default for compacted SSTs can lead to a lot of write amplification and slow things down. 256MiB was a much better default for him.  In general, I think that makes sense for others, too. The cost is 4x the number of SSTs listed in the manifest and on list() calls to `compacted`. If that's an issue for users, they can set their SST size to 1GiB.
Fixes #602, #646

Default to Foyer cache and 256MiB `max_sst_size`

---

Cargo.lock
slatedb/Cargo.toml

foyer v0.17.3, uses `BuildHasherDefault<AHasher>` as the default hasher to prevent from inconsistent hash result between different instances, but even with BuildHasherDefault<AHasher>, it only guarantees consistent results in the same run, not between runs.
foyer v0.17.4 fix it by switching the default hasher to xxhash64.
FYI: 
- PR: https://github.com/foyer-rs/foyer/pull/1029
- Issue: https://github.com/foyer-rs/foyer/issues/1018
- Discussion: https://github.com/foyer-rs/foyer/discussions/1010#discussioncomment-13593303

fix: upgrade foyer to fix recovery

---

slatedb/src/compaction_execute_bench.rs
slatedb/src/compactor.rs
slatedb/src/compactor_executor.rs
slatedb/src/wal_buffer.rs

I added a `CompactionProgressTracker` to `compactor.rs`. I updated the compactor to log the compaction progress along with the compaction state when the ticker fires in the event loop.
Here's what it looks like:
```
2025-07-02T22:42:44.903438Z DEBUG slatedb::compactor: compaction progress id=0a1e6fbe-c117-4c52-b9cf-6f9af317bb96 current_percentage="2%" processed_bytes=13802880 estimated_total_bytes=540058533
```
This will give wildly inaccurate results when compression is used since we're using compressed bytes when estimating size, but uncompressed bytes when getting the size of key/value pairs. IMO, it's still useful for tracking raw byte progress. Once we store actual byte or row count information in metadata, we can use it here to calculate accurate progress.

Add compactor progress

---

.github/workflows/python.yaml
RELEASE.md

After jumping through man hoops, I've gotten 0.7.0 published to PyPI. I've updated the release documentation to describe how to do this.
I also decided to make the Python release run against a tag, not main. This seems safer and will keep Python releases in lock-step with the Rust crate.

Update RELEASE.md with Python binding instructions

---

CONTRIBUTING.md
README.md

I've had some project ideas rattling around in the back of my head. I want to get them written down so people can find them. I considered GH issues, GH discussions, an `awesome-slatedb` repo, or adding to the docs. Ultimately, I settled on a quick little section in `CONTRIBUTING.md` and a reference in the `README.md` If the list grows or we add more detail, we can move it elsewhere. `CONTRIBUTING.md` seemed most expedient.

Add some project ideas

---

slatedb-py/src/lib.rs
slatedb-py/tests/test_basic_operations.py

I implemented a version of slatedb-py's scan_iter using mpsc.
Theoretically, there should be a simpler way, but due to lifecycle constraints, I could only find this solution.

feat: add scan iterator functionality to PySlateDB and PySlateDBReader

---

.github/workflows/pr.yaml
scripts/backtrace-on-timeout.sh
slatedb/src/compactor_executor.rs

When a writer is finished, the compaction process is recording 0 as the size, instead of the size of the current bytes processed until that point.
I was looking at these two lines while trying to implement #676, and it seems wrong. Since this is a small change, I rather get it out while I try to figure out how to implement #676 correctly.

Record bytes_compacted correctly.

---

slatedb/src/compactor_executor.rs
slatedb/src/mem_table_flush.rs
slatedb/src/utils.rs

I found that our current ULID generator is non-deterministic because it uses the `ulid` crate to get time, which always uses system time, not our `SystemClock`. Fixed this by adding a param to take our clock.
I considered separating ULID and UUID generation out so we can have a ULID struct that contains a clock, but it felt clunky to have two different ways to generate IDs. This way, the ULID and UUID generation continue to piggyback off of any `RngCore`, and we only need to pass a clock when we're generating ULIDs, which is relatively limited.

Add `gen_ulid` clock param

---

.config/nextest.toml
.github/workflows/nightly.yaml
Cargo.lock
Cargo.toml
slatedb-dst/Cargo.toml
slatedb-dst/README.md
slatedb-dst/src/dst.rs
slatedb-dst/src/lib.rs
slatedb-dst/src/utils.rs
slatedb-dst/tests/simulation.rs

This PR integrates the DST into the nightly Github workflow.
- Adds a `test_dst_nightly` test to simulation.rs.
- Adds a `slow` cfg to `Cargo.toml` to signal slow tests should be run.
- Updates `nightly.yaml` to run the DST on a WarpBuild instance.
- Adds a `DstDuration` param that can be either `Iterations` or `Duration` (wall-clock time) to the `run_simulation`. This allows us to run simulations for a set amount of time rather than a set number of iterations.
- Update `nextest.toml` to include a new `dst-nightly` profile.
- Update docs and README.md
`test_dst_nightly` runs a separate DST on each core of the host machine. The tests run in parallel for 50 minutes.
Future improvements:
- Fail as soon as a handle finishes rather than joining them sequentially.
- Make `test_dst_nightly` use …

Add a nightly DST test

---

.github/workflows/nightly.yaml
slatedb-dst/src/dst.rs
slatedb-dst/tests/simulation.rs

The GH action runner is killing our DST tests for some reason. I'm not totally clear why, but I'm attempting to give it some headroom.

Cap DST nightly at 90% CPU usage

---

.github/workflows/nightly.yaml

Nightly DSTs are still failing on WarpBuild with the core usage dropped to 90%. It ran a lot longer (16m instead of 5m), but still got killed. I'm switching to GH action runners to see if it's an issue with WarpBuild (or Hetzner) machines.

Run nightly DST on ubuntu-latest

---

.github/workflows/nightly.yaml
slatedb-dst/README.md
slatedb-dst/src/dst.rs
slatedb-dst/src/utils.rs
slatedb-dst/tests/simulation.rs

This PR adds a new environment variable for DSTs called `SLATEDB_DST_ROOT`. The `slow` DST uses this as the root to create a `LocalFileSystem` `object_store` for each `Db`. Previously, we were using `InMemory`, which was accruing a ton of memory because GC wasn't running very frequently and we were creating a ton of garbage in the test.

Use LocalFileSystem for nightly DST

---

.github/workflows/release-website.yaml

I just realized that the versions I configured are quite old. They throw some warnings because of deprecated GHA features.
@criccomini

Update action versions to release the website.

---

slatedb/src/config.rs
website/src/content/docs/docs/architecture.md

It looks like the garbage collector options were changed from "poll_interval" to just "interval", but docs were not updated to reflect.
The compactor still uses "poll_interval", so care was taken to _not_ update the docs. Searched through code for instances of `poll_interval`, determined if it was for the garbage collector or compactor, and replaced as appropriate.

Fix documentation issue for garbage collection: "poll_interval" -> "interval"

---

website/src/styles/custom.css

The theme selector in the mobile menu was showing when you opened the menu.
Before:
After:
/cc @criccomini

Hide the website's theme selector on mobile views.

---

.github/workflows/nightly.yaml

#731 migrated our website to the main repo. We were uploading pprof .pb files to the `slatedb-website` repo. This PR uploads those files to pprof.me for viewing instead.

Upload pprof files to pprof.me

---

.github/workflows/nightly.yaml
slatedb-bencher/benchmark-db.sh
slatedb-dst/tests/simulation.rs

Attempts to prevent out-of-disk-space errors when running `nightly.yaml` DSTs.

Use `cwd` for `SLATEDB_DST_ROOT` in DST tests

---

website/src/content/docs/docs/performance.md

The website still linked to old `slatedb-website` paths for microbenchmark and bencher benchmark results. This information is now stored in the nightly Github action's summary. This PR updates the links and references to point to the Github action.

Update performance docs on website

---

slatedb/src/reader.rs

The range to scan the database can be owned by the DbIterator since it's not used later.

Remove extra clone creating a DbIterator.

---

slatedb/src/batch_write.rs
slatedb/src/mem_table.rs
slatedb/src/wal_buffer.rs

this pr addes a write lock for batch write operations for WAL appends.
this lock may help us ensure the wal flushing always happen in the write batch boundary.
fixes #762

fix(wal): ensure batch wal append in atomic

---

slatedb/src/compactor.rs
slatedb/src/mem_table_flush.rs

This one seems like a bit too verbose and may make users believe there's an issue when there's not.

Make "conflicting manifest" log debug

---

.github/workflows/nightly.yaml

The nightly benchmark was filled with a lot of chatty debug logs from the WAL buffer. Disabling debug so I can see the logs more clearly.

Set `RUST_LOG` to info for nightly benchmark

---

website/src/pages/slatedb-go.astro

According to this:
https://go.dev/ref/mod#vcs-find
We need to specify a subdirectory in our meta for Go module vanity URLs.

Add subdirectory to go meta url

---

.github/workflows/release-website.yaml
.github/workflows/release.yaml
website/src/pages/slatedb-go.astro

Go module tagging for subdirectories requires the format `subdir/v0.0.0`. I'm adding a `slatedb-go/go/v0.0.0` tag to the release process so users will be able to `go get slatedb.io/slatedb-go`.

Add Go module tag to release process

---

slatedb/src/manifest/store.rs
slatedb/src/tablestore.rs
slatedb/src/test_utils.rs
slatedb/src/wal_buffer.rs

This is a follow-on to #819. That PR added retry support for both manifest and SST writes. This PR adds basic unit tests to verify that the retries actually happen. It also removes the custom WAL buffer retry logic since retries are handled through the `TableStore` now.

Add retry tests for manifest/WAL writes

---

.github/workflows/release.yaml

The most recent (0.8.0) release failed because the release.yaml does not set a github bot name or email. This PR fixes that.

Set github action bot name and email

---

slatedb/src/mem_table_flush.rs

We're logging display info, not debug info, when logging errors in the memtable flusher.

Add memtable flush logs

---

slatedb-dst/src/utils.rs

Use .min() when determining min_compaction_sources in DST

---

slatedb/src/seq_tracker.rs

See RFC-0012 for the implementation details, but it effectively implements the seq_tracker using a simpler (non-tiered) double-array with a simple remove-every-other-entry downsampling strategy.

modify seq_tracker implementation to match RFC-12

---

slatedb/src/db/builder.rs
slatedb/src/lib.rs
slatedb/src/manifest/store.rs
slatedb/src/retrying_object_store.rs
slatedb/src/store_provider.rs
slatedb/src/tablestore.rs
slatedb/src/test_utils.rs
slatedb/src/utils.rs

It appears I missed many spots where we interact with the object store. Users are reporting failures for list and get operations:
https://github.com/Barre/ZeroFS/issues/143
Rather than trying to chase all of these down, I created a `RetryingObjectStore`. It uses the same retry logic for all `ObjectStore` operations. All errors are retried except `AlreadyExists`, `Precondition`, and `NotImplemented`. I realized that, with this approach, we no longer need to worry about `ManifestVersionExists` and `Fenced` because the `TableStore` and `ManifestStore` both convert `AlreadyExists` to the appropriate `SlateDBError`.

Wrap object stores in `RetryingObjectStore`

---

slatedb/src/error.rs

Pretty self explanatory. At the moment this returns a reference since `ErrorKind` is not `Copy`. It might also be a good idea to mark it as `non_exhaustive` so adding new error kinds is not a breaking change now that they're exposed.

Expose errors' `ErrorKind`

---

slatedb/src/compaction_execute_bench.rs
slatedb/src/compactor.rs
slatedb/src/compactor_executor.rs
slatedb/src/db/builder.rs
slatedb/src/dispatcher.rs

Update the compactor to use `MessageDispatcher`. I tried to do this in the least invasive way possible. The implementation creates the `MessageDispatcher` inside `Compactor::run_async_task`. I like this pattern because it makes it pretty straight-forward to create a Compactor and run it outside of the DB (in a separate process/on a separate machine).
If the PR feels unwieldy, I suggest looking at the changes commit-by-commit.
Part of #776

Implement MessageHandler for CompactorEventHandler

---

slatedb-go/README.md
slatedb-go/go/batch_test.go
slatedb-go/go/config.go
slatedb-go/go/config_test.go
slatedb-go/go/db.go
slatedb-go/go/db_test.go
slatedb-go/go/iterator_test.go
slatedb-go/go/slatedb.h
slatedb-go/src/config.rs
slatedb-go/src/db.rs
slatedb-go/src/db_reader.rs
slatedb-go/src/object_store.rs

Using settings json as expected by the rust dbBuilder instead of creating a custom SlateDBOptions. This change makes the ffi/go usage closer to rust usage, and provides configuration options which were previously missing. It also adds missing support for providing settings through file, env, or auto-detection.
Also changes the previous `Open` method to use all defaults, and removed the SlateDBOptions argument. Advanced usage can use the builder methods instead.

Expose db builder through ffi, remove SlateDBOptions

---

slatedb/src/db.rs
slatedb/src/error.rs

This does exactly what the title says.
Other options for fencing errors would be to add a `fenced` boolean field to `ErrorKind::Permission`, or to rename that variant or guarantee that it only applies to fencing. In any case users should be able to tell whether an error is due to fencing, and in my opinion it shouldn't be mixed with any other error kinds.
As for the other part of the changes, they were already discussed in #892.
Fixes #881

Expose fencing errors & mark `ErrorKind` as `non_exhaustive` and `Copy`

---

slatedb/src/batch_write.rs
slatedb/src/checkpoint.rs
slatedb/src/db.rs
slatedb/src/mem_table_flush.rs
slatedb/src/wal_buffer.rs

After various dispatcher.rs migrations, several issues surfaced:
1. `mem_table_flush.rs` was always returning `Ok(())` in its event handler (even when `flush_and_record` or `write_checkpoint_safely` failed).
2. A race condition in `batch_write.rs` surfaced. We call `wal_buffer.append()` to add rows, then later we get the `current_wal` to use when notifying durable writes. It's technically possible for `flush_interval` to trigger a WAL flush between these two steps. If that happens, the `current_wal` we return is not the WAL that the rows were written to (it's already been frozen and potentially flushed). This was causing our test to hang indefinitely since the second WAL never gets flushed.
3. We had the test set to a max L0 SST byte size of 128, which we were writing. This led to a race …

Fix `test_should_recover_imm_from_wal_after_flush_error`

---

.github/workflows/nightly.yaml

We have a number of tests that make assumptions about ordering and timing. Such tests often break when we refactor our code. To detect these issues going forward, I'm adding a little flaky test detector that runs tests in a loop for 15 minutes every day.

Add flaky test detection

---

schemas/manifest.fbs
slatedb-go/go/slatedb.h
slatedb/src/batch_write.rs
slatedb/src/compactor_state.rs
slatedb/src/db.rs
slatedb/src/db_reader.rs
slatedb/src/db_state.rs
slatedb/src/flatbuffer_types.rs
slatedb/src/generated/manifest_generated.rs
slatedb/src/mem_table_flush.rs
slatedb/src/oracle.rs
slatedb/src/seq_tracker.rs
slatedb/src/size_tiered_compaction.rs
slatedb/src/wal_buffer.rs

Replaces #773 which was closed in favor of the simpler design.
You can review the commits in order if you'd like, they basically do this:
- Wire the new sequence tracker through the manifest codec, memtable flush, and oracle so every flush persists the latest tracking state and restarts restore it.
- Extend the oracle to own the live tracker, update it on each committed batch, and keep the in-memory copy in sync when manifests change.
- Add an end-to-end test that writes a few batches, flushes to L0, reloads the manifest, and proves the tracker survives a restart.
This is the second to last PR in fixing #685 - the next PR will make sure the iterators use the mapping to filter out records appropriately.

wire in sequence tracker [RFC-0012]

---

slatedb/src/db.rs
slatedb/src/dispatcher.rs
slatedb/src/error.rs
slatedb/src/garbage_collector.rs
slatedb/src/mem_table_flush.rs
slatedb/src/wal_buffer.rs

A clean shutdown in SlateDB (`db.close()`) currently sets a `SlateDBError::BackgroundTaskShutdown` in `db_state.rs`'s `error` field. We then special case this error type all over the place to determine when we're shutdown cleanly. This is confusing and brittle.
I've removed `BackgroundTaskShutdown`. `dispatcher.rs` now returns `Ok(())` when it's shutdown cleanly. If a dispatcher run_loop returns with an `Err(...)`, it still sets the `error` field in `db_state.rs`. Doing so immediately halts all other dispatchers and blocks future calls to the DB.
I originally thought we should convert `db_state.rs`'s `error: WatchableOnceCell<SlateDBError>,` to be `shutdown_result: WatchableOnceCell<Result<(), SlateDBError>>`. The idea was that we'd set the field to `Ok(())` on shutdown to signal that the …

Replace `BackgroundTaskShutdown` with a clean shutdown

---

slatedb/src/db.rs

test_get_with_object_store_cache_stored_files was failing randomly on the Windows cross build. I'm unable to reproduce the issue locally, but I did notice that the helper the tests uses wraps the object store in two `FsCacheStorage` and points them to the same directory.
I inspected the temp directory and found that it held both a 1kib and 4mib part file (one for each cache). I suspect there's a race between these two caches that is causing the failure. I've updated the helper to disable the internal object store cache and _only_ use the one we explicitly set in the test.

Don't double-cache object store in test helper

---

slatedb/src/compactor.rs
slatedb/src/compactor_state.rs
slatedb/src/size_tiered_compaction.rs

- Add a provided validation hook to `CompactionScheduler` so each scheduler can validate proposed compactions.
- Move validation responsibility from `CompactorState` to schedulers; keep compactor as the enforcement point.
- Use public `crate::error::Error` at the trait boundary; map to internal `SlateDBError` inside the compactor.
- Relocate/adjust invalid-compaction tests to the size-tiered scheduler, fixing flakiness and type issues.
- Avoid “private type in public API” by not exposing `SlateDBError` in a public trait.
- Let each scheduling policy own its validation logic (policy-specific rules).
- Remove duplicate or conflicting validation paths (state vs. scheduler).
- Keep the compactor policy-agnostic and simply enforce the scheduler’s decision.
- `slatedb/src/compactor.rs`
- …

[Minor]Refactor compaction validation to scheduler; replace SlateDBError in trait API

---

slatedb/src/cached_object_store/object_store.rs

Improve object_store `test_save_result_not_aligned`
- this test asserts that `CachedObjectStore` has the expected behaviors when the object is not aligned with chunked part_size
```
| p0 (1024 bytes) | p1 (1024 bytes) | p2 (1024 bytes) | p3 (32 bytes) | 
```
- before: not asserting the last unaligned part p3
- after: assert that the unaligned part exists in cache also

Improve object_store test_save_result_not_aligned
