src/compaction_execute_bench/README.md

Added README.md with usage instructions for SlateDB Compaction Benchmarking Tool

Added README.md with usage instructions for compaction_execute_bench

---

.github/workflows/pr.yaml
src/sst.rs

test(sst): add test for compression

---

src/db.rs

fixes #86
as the issue suggested:
> 1. detaching this method from self and calling it before initializing DbInner. The downside is we can't use member methods of DbInner like maybe_freeze_wal
> 2. accumulating kv-pairs in memory and bulk-applying the writes
I was considering the 2nd approach, but I found that we already have an iterator. so instead of using a memory buffer, it might be more memory-efficient to simply apply the iterator directly to the memtable.
in this PR, I tried to increase the lock granularity by using a larger lock when applying an SST iterator to the memtable.
the downside of this approach is that the lock spans across an `.await` point, which should be avoided in most cases, a slow `.await` might cause this lock to be held too long. however, this function is only …

refactor: reduce locks on apply wal on every kv

---

Cargo.lock
Cargo.toml
src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_executor.rs
src/compactor_state.rs
src/db.rs
src/sst.rs
src/tablestore.rs

Add Loggin infra to SlateDB

---

src/compactor_state.rs
src/config.rs

Fixes: #157
~~sorry, moving this to draft, i forgot to run the tests locally, i will mark this for review once i run them~~
`cargo test` passed locally

Increase L0 SST size to 64MiB

---

src/sst.rs

sst: compress bloom filters

---

src/compaction_execute_bench.rs
src/compactor.rs
src/compactor_executor.rs
src/compactor_state.rs
src/db.rs
src/db_state.rs
src/flatbuffer_types.rs
src/flush.rs
src/size_tiered_compaction.rs
src/sorted_run_iterator.rs
src/sst_iter.rs
src/tablestore.rs

Rename SSTableHandle to SsTableHandle

---

Cargo.lock
Cargo.toml
src/inmemory_cache.rs

As [promoted](https://github.com/slatedb/slatedb/issues/9#issuecomment-2345154457) and discussions in Discord, let's try integrate foyer into slatedb as the in-memory cache as the first step.

feat: add foyer as an in-memory option

---

specs/README.md
specs/kvstore/KeyValueStore.fizz

Adds a fizzbee model for SlateDB KeyValue store.

Initial fizzbee model for the basic slatedb keyvalue store

---

Cargo.toml
src/s3_bench/README.md
src/s3_bench/main.rs
src/s3_bench/run.sh

See src/s3-bench/README.md for details.

S3 Benchmarking Tool

---

rfcs/0003-timestamps-and-ttl.md

See #218 for historical context.

add design for timestamps and ttl

---

src/db_state.rs

Using debug logs for db internal operations

---

src/db.rs

Use fp_registry when we create it in tests

---

rfcs/0004-checkpoints.md

Updates the checkpoints RFC based on @vigneshc feedback about soft-deleting as part of the hard-delete flow, and then subsequent discussion about checking for soft deletes when creating checkpoints.

update checkpoints rfc based on feedback about destroyed_at_s

---

src/config.rs
src/db.rs

chore(db): Make DbOptions Debugable and log on JSON encode failure.

---

src/admin.rs
src/garbage_collector.rs

see https://github.com/slatedb/slatedb/pull/343#discussion_r1857447954

refactor interrupt handler in gc [MINOR]

---

.github/workflows/pr.yaml
src/sorted_run_iterator.rs
src/sst.rs
src/sst_iter.rs

It was bugging me that every time I ran `cargo clippy --all-targets --all-features` it would complain about the tests. Fixing that here.

update CI/CD to run clippy on tests [MINOR]

---

src/mem_table.rs

pretty much self-explanatory; the root issue was excluding tombstone attributes from the size calculation

Prevent memtable size underflow.

---

src/mem_table.rs

We can avoid searching in the skiplist for the previous value in order to do memory tracking. The API is not super friendly (unlike Map#put in Java for example), but we can do this using compare_insert.
This shows roughly 25% improvement for the following benchmark: https://gist.github.com/dmvk/23b0feb6c8ad051cd95e1d224f665846

Improve memtable throughput by avoiding unnecssary SkipList search.

---

src/garbage_collector.rs

I wasn't totally happy with the way I had implemented the tickers/statuses in #343 so I have a minor PR here to refactor this here. 
The change does a few minor things:
1. Introduces `GcTask` as a trait, and three implementations `ManifestGcTask`, `WalGcTask`, `CompactedGcTask`
2. Moves all methods specific to one resource type into corresponding implementation of `GcTask`
3. Moves a few minor things such as ticker creation into `DirGcStatus` for simplicity
Mostly an opportunity for me to level up my Rust skills, so feel free to reject it if you don't like it!

refactor garbage collector into individual tasks

---

.github/FUNDING.yml

I'm adding Commonhaus's open collective account as a link to SlateDB. Those that wish to support SlateDB should donate to Commonhaus.

Add Commonhaus FUNDING.yml

---

README.md

https://github.com/slatedb/slatedb/issues/409

Add scan range usage to readme

---

src/sst.rs

Refactor the test to table driven approach to better organize and easier addition of new test cases. 
[Issue](https://github.com/slatedb/slatedb/issues/341)

chore: Apply table driven test for sst.rs

---

.github/workflows/pr.yaml

Suggested [here](https://github.com/slatedb/slatedb/pull/468#discussion_r1934917621). It is useful to enable `--all-features` when running doctests.

Doc test all features

---

src/db.rs
src/db_stats.rs

Adds stats for bloom filter positives, negatives, and false positives.

add bloom filter pos/neg/false pos stats

---

src/sst.rs
src/utils.rs

See https://github.com/slatedb/slatedb/issues/472

Reduce size of index blocks using lower bound index key

---

src/block.rs
src/compactor.rs
src/compactor_state.rs
src/db.rs
src/db_common.rs
src/filter.rs
src/mem_table.rs
src/row_codec.rs
src/sst.rs
src/tablestore.rs
src/wal_replay.rs

Work of #77 . Provides a more precise method for calculating SST sizes for memtable.

More accurate SST size estimation for the memtable

---

src/mem_table.rs

chore: Fix typo

---

CONTRIBUTING.md

doc: fix contributing guide nextest script

---

slatedb/src/garbage_collector.rs

Prevent tasks to start if the Tokio runtime is shutting down.

fix(gc): Check the cancellation token before starting any gc tasks.

---

Cargo.lock
slatedb/Cargo.toml

Key updates: https://github.com/foyer-rs/foyer/pull/1012

fix(foyer): bump to foyer v0.17.3 to fix recovery

---

slatedb/src/config.rs

See https://github.com/slatedb/slatedb/issues/596 for context

fix docstrings about manifest poll interval

---

slatedb/src/sst_iter.rs

#394 Apply binary search to SstIterator::seek instead of advancing on block each time.

Add binary search to SstIterator::seek

---

slatedb/src/db.rs
slatedb/src/mem_table_flush.rs

Clean up SST file if writer is fenced

---

slatedb/src/db/builder.rs
slatedb/src/garbage_collector.rs

While playing with the compactor, I realized that the GC doesn't need the tokio_handle except when `start_in_bg_thread` is called. Providing it as a parameter feels way more intuitive than using the builder/::new method (similar to the cleanup_fn).

Move GC tokio_handle to start_in_bg_thread

---

slatedb/src/config.rs
slatedb/src/error.rs
slatedb/src/utils.rs

Follow up of #697 addressing minor comments in that PR.
- Make the messages consistent.
- Add missing rustdocs for the timeout function.
/cc @criccomini

Merge SettingsError into SlateDBError.

---

.github/instructions/fizzbee.instructions.md
specs/README.md

FizzBee can be a bit tricky do work with and LLMs don't know much about it yet. @jayaprabhakar supplied us with a [Copilot instruction file](https://docs.github.com/en/copilot/how-tos/configure-custom-instructions/add-repository-instructions). I've added it and updated the `specs/README.md` file to alert users that they might wish to include it in their IDE's rule/instruction files as well.

Add FizzBee LLM instructions to `.github/instructions`

---

slatedb-dst/src/dst.rs

Make put_probability random.

---

README.md

Adding a Dosu link for its `/ask` interface.

Add Dosu bot to README.md

---

slatedb-bencher/benchmark-db.sh

Mermaid doesn't seem to support multiple bar charts; they overlap and end up hiding each other. I've gone back to line charts. I've also made the chart vertical so date/checksum are visible.

Adjust nightly perf charts more

---

slatedb-dst/src/utils.rs

I accidentally missed some formatting in #823.

Fix DST formatting to make build pass

---

rfcs/0002-compaction.md

Fix example in the compaction RFC.

[Minor]Fix example in the compaction RFC

---

website/src/pages/slatedb-go.astro

Fix go import

---

slatedb/src/compactor_state.rs

Add validation for submitted compactions
https://github.com/slatedb/slatedb/issues/96
https://github.com/slatedb/slatedb/pull/156/files

Add validation for submitted compactions

---

slatedb/src/compactor.rs
slatedb/src/db.rs
slatedb/src/test_utils.rs

`test_should_tombstones_in_l0` failed in a recent nightly:
https://github.com/slatedb/slatedb/actions/runs/18001434698/job/51211440101
There is a race condition in this test where the compactor can see only the first write when the flush is triggered. This is because the compactor maintains its own view of the DB state (manifest) independently of the writer. It refreshes this view periodically. It is possible to have this sequence of events:
1. db.put(k1, v1) (line 730 in `compactor.rs`)
2. k1 put is flushed to l0 SST
3. writer updates manifest with l0 SST
4. compactor refreshes (`CompactorEventHandler::handle_ticker`) its manifest and sees a single L0 SST
5. db.put(k2, v2) (line 731 in `compactor.rs`)
6. db.flush() (line 732 in `compactor.rs` noop since the previous put's were …

Wait for both writes in test_should_tombstones_in_l0

---

Cargo.lock
examples/Cargo.toml
examples/README.md
examples/src/google_cloud_storage.rs
website/astro.config.mjs
website/src/content/docs/docs/tutorials/abs.mdx
website/src/content/docs/docs/tutorials/gcs.mdx
website/src/content/docs/docs/tutorials/s3.mdx

docs: add example and documentation for GCS support
